Repository camunda/camunda-docs, pull requests merged in 2021-12, with the labels that each got.

#518 Update Tasklist Graphql API docs
  docs/apis-clients/tasklist-api/directives/include.mdx
  docs/apis-clients/tasklist-api/directives/skip.mdx
  docs/apis-clients/tasklist-api/directives/specified-by.mdx
  docs/apis-clients/tasklist-api/generated.md
  docs/apis-clients/tasklist-api/inputs/task-query.mdx
  docs/apis-clients/tasklist-api/inputs/variable-input.mdx
  docs/apis-clients/tasklist-api/mutations/claim-task.mdx
  docs/apis-clients/tasklist-api/mutations/complete-task.mdx
  docs/apis-clients/tasklist-api/mutations/delete-process-instance.mdx
  docs/apis-clients/tasklist-api/mutations/unclaim-task.mdx
  docs/apis-clients/tasklist-api/objects/form.mdx
  docs/apis-clients/tasklist-api/objects/task.mdx
  docs/apis-clients/tasklist-api/objects/user.mdx
  docs/apis-clients/tasklist-api/objects/variable.mdx
  docs/apis-clients/tasklist-api/queries/form.mdx
  docs/apis-clients/tasklist-api/queries/task.mdx
  docs/apis-clients/tasklist-api/queries/tasks.mdx
  docs/apis-clients/tasklist-api/queries/variable.mdx
  docs/apis-clients/tasklist-api/queries/variables.mdx
  docusaurus.config.js
Labels: component/tasklist

#441 Add Zeebe secure cluster communication docs
  docs/self-managed/zeebe-deployment/security/client-authorization.md
  docs/self-managed/zeebe-deployment/security/secure-client-communication.md
  docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md
  docs/self-managed/zeebe-deployment/security/security.md
  sidebars.js
Labels: release/1.3.0

#504 Document Zeebe's Rebalancing API
  docs/self-managed/zeebe-deployment/operations/index.md
  docs/self-managed/zeebe-deployment/operations/rebalancing.md
  sidebars.js
Labels: release/1.3.0

#529 chore(go): bump go version and zbc import
  docs/apis-clients/go-client/get-started.md
  docs/apis-clients/go-client/index.md
  docs/self-managed/zeebe-deployment/security/client-authorization.md
  docs/self-managed/zeebe-deployment/security/secure-client-communication.md
Labels: component/zeebe, dependencies

#462 Describe assignment definitions for user tasks
  docs/components/modeler/bpmn/user-tasks/user-tasks.md
Labels: release/1.3.0

#456 Add IP Whitelists Doc
  docs/components/cloud-console/introduction.md
  docs/components/cloud-console/manage-clusters/img/cluster-detail-create-ip-whitelist.png
  docs/components/cloud-console/manage-clusters/img/cluster-detail-ip-whitelists.png
  docs/components/cloud-console/manage-clusters/manage-ip-whitelists.md
  sidebars.js
Labels: release/1.3.0

#467 feat(usage): add section about usage history
  docs/components/cloud-console/manage-organization/img/trial-usage-history.png
  docs/components/cloud-console/manage-organization/update-billing-reservations.md
  docs/components/cloud-console/manage-organization/usage-history.md
  sidebars.js
Labels: release/1.3.0
