Repository camunda/camunda-docs, pull requests merged in 2021-02, with the labels that each got.

#172 Adjust go get started guide
  docs/product-manuals/clients/go-client/get-started.md
Labels: lgtm, size/XS

#166 chore(docs): fix left overs
  docs/product-manuals/zeebe/deployment-guide/operations/resource-planning.md
  docs/product-manuals/zeebe/deployment-guide/operations/upgrade-zeebe.md
Labels: approved, lgtm, size/XS

#168 Update review process guideliness
  howtos/documentation-guidelines.md
Labels: size/S

#177 Clarify job delivery guarantees/idempotency requirements
  docs/product-manuals/concepts/job-workers.md
Labels: size/XS

#171 Pricing & plan updates
  docs/product-manuals/cloud-console/manage-organization/update-billing-reservations.md
  docs/product-manuals/cloud-console/manage-plan/available-plans.md
  docs/product-manuals/cloud-console/manage-plan/professional-plan/billing-parameters.md
  docs/product-manuals/cloud-console/manage-plan/professional-plan/overview.md
  docs/product-manuals/cloud-console/manage-plan/trial-plan.md
  docs/product-manuals/cloud-console/manage-plan/upgrade-to-professional-plan.md
  sidebars.js
Labels: size/L
