Repository camunda/camunda-docs, pull requests merged in 2021-07, with the labels that each got.

#321 Added Spring to community clients (fixes https://github.com/camunda-c…
  docs/product-manuals/clients/java-client/index.md
  docs/product-manuals/clients/other-clients/index.md
  docs/product-manuals/clients/other-clients/spring.md
  docs/product-manuals/clients/overview.md
Labels: size/S

#322 Fixed Webhook alerts JSON body
  docs/product-manuals/cloud-console/manage-clusters/manage-alerts.md
Labels: needs-ok-to-test, size/S

#324 Origin/editorial review
  docs/product-manuals/clients/build-your-own-client.md
  docs/product-manuals/clients/cli-client/get-started.md
  docs/product-manuals/clients/cli-client/index.md
  docs/product-manuals/clients/go-client/get-started.md
  docs/product-manuals/clients/go-client/index.md
  docs/product-manuals/clients/java-client-examples/cluster-topology-request.md
  docs/product-manuals/clients/java-client-examples/data-pojo.md
  docs/product-manuals/clients/java-client-examples/index.md
  docs/product-manuals/clients/java-client-examples/job-worker-open.md
  docs/product-manuals/clients/java-client-examples/process-deploy.md
  docs/product-manuals/clients/java-client-examples/process-instance-create-nonblocking.md
  docs/product-manuals/clients/java-client-examples/process-instance-create-with-result.md
  docs/product-manuals/clients/java-client-examples/process-instance-create.md
  docs/product-manuals/clients/java-client/index.md
  docs/product-manuals/clients/java-client/job-worker.md
  docs/product-manuals/clients/java-client/logging.md
  docs/product-manuals/clients/java-client/testing.md
  docs/product-manuals/clients/other-clients/index.md
  docs/product-manuals/clients/other-clients/javascript.md
  docs/product-manuals/clients/overview.md
Labels: size/L
