Repository camunda/camunda-docs, pull requests merged in 2022-01, with the labels that each got.

#548 Document Zeebe's Priority Election
  docs/components/zeebe/technical-concepts/partitions.md
  docs/self-managed/zeebe-deployment/configuration/fixed-partitioning.md
  docs/self-managed/zeebe-deployment/configuration/priority-election.md
  docs/self-managed/zeebe-deployment/operations/rebalancing.md
  sidebars.js
Labels: release/1.3.0

#547 feat(optimize): add ccsm configuration setup documentation
  docs/self-managed/optimize-deployment/setup.md
  sidebars.js
Labels: release/1.3.0, component/optimize

#537 Update Operate-Tasklist screenshots for variables panel
  docs/components/operate/userguide/img/operate-incident-resolved-path_dark.png
  docs/components/operate/userguide/img/operate-incident-resolved-path_light.png
  docs/components/operate/userguide/img/operate-incident-resolved_dark.png
  docs/components/operate/userguide/img/operate-incident-resolved_light.png
  docs/components/operate/userguide/img/operate-process-retry-incident_dark.png
  docs/components/operate/userguide/img/operate-process-retry-incident_light.png
  docs/components/operate/userguide/img/operate-view-instance-detail_dark.png
  docs/components/operate/userguide/img/operate-view-instance-detail_light.png
  docs/components/operate/userguide/img/operate-view-instance-edit-icon_dark.png
  docs/components/operate/userguide/img/operate-view-instance-edit-icon_light.png
  docs/components/operate/userguide/img/operate-view-instance-incident_dark.png
  docs/components/operate/userguide/img/operate-view-instance-incident_light.png
  docs/components/operate/userguide/img/operate-view-instance-save-variable-icon_dark.png
  docs/components/operate/userguide/img/operate-view-instance-save-variable-icon_light.png
  docs/components/tasklist/img/tasklist-start-screen_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-claim_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-claimed-by-me-empty_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-claimed-by-me-list_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-claimed-by-me_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-complete-task_light.png
  docs/components/tasklist/userguide/user-interface/img/tasklist-task-completed_light.png
Labels: release/1.3.0

#494 docs(feat): Add contributor guide, CoC + docs workflow
  CONTRIBUTING.MD
  code-of-conduct.md
  howtos/documentation-workflows.MD
  static/img/CommitChanges.png
  static/img/EditThisPage.png
  static/img/WebBasedDocumentation.png
Labels: kind/enhancement, component/documentation

#578 fix(docs): correct link formatting
  CONTRIBUTING.MD
Labels: kind/cleanup
