Repository camunda/camunda-docs, pull requests merged in 2022-09, with the labels that each got.

#1226 fix: use lint-staged correctly (to decrease commit time)
  package.json
Labels: kind/bug, component:docs, dx

#1243 move import statement to top of file
  docs/guides/getting-started-orchestrate-microservices.md
  versioned_docs/version-8.0/guides/getting-started-orchestrate-microservices.md
Labels: kind/bug, component:docs

#1238 feat (optimize/3.8.0): redirect rules for optimize/3.8.0 docs
  static/.htaccess
Labels: component:docs, dx, epic:optimize-versions

#1239 chore (optimize/3.8.0): revert "remove vNext and optimize docs from sitemap"
  docusaurus.config.js
Labels: component:docs, dx, epic:optimize-versions

#1235 feat: show correct versions in navbar based on which docs you're viewing
  src/theme/NavbarItem/index.js
Labels: component:docs, dx, epic:optimize-versions

#1270 fix?: attempt to fix mixpanel events
  src/theme/Footer/index.js
Labels: kind/bug, component:docs, dx

#1271 chore: tune logging of errors for mixpanel logic
  src/theme/Footer/index.js
Labels: kind/cleanup, component:docs, dx

#1272 style(formatting): technical review using templates
  docs/components/modeler/desktop-modeler/element-templates/using-templates.md
Labels: component:connectors

#1163 docs(google drive): add Google Drive OOTB connector doc
  docs/components/integration-framework/connectors/img/connectors-googledrive-get-parent-folder-id.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-get-template-id.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-jwt-bearer.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-jwt-refresh.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-new-file-filled.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-new-folder-filled.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-processed-template-example.png
  docs/components/integration-framework/connectors/img/connectors-googledrive-template-example.png
  docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview.md
  docs/components/integration-framework/connectors/out-of-the-box-connectors/googledrive.md
  sidebars.js
Labels: component:connectors

#1209 docs(aws sqs): add AWS SQS OOTB connector doc
  docs/components/integration-framework/connectors/img/connectors-aws-sqs-filled.png
  docs/components/integration-framework/connectors/img/connectors-aws-sqs-message-attributes.png
  docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview.md
  docs/components/integration-framework/connectors/out-of-the-box-connectors/aws-sqs.md
  sidebars.js
Labels: component:connectors

#1275 change io.zeebe to io.camunda
  versioned_docs/version-1.1/components/clients/java-client/index.md
  versioned_docs/version-1.2/apis-clients/java-client/index.md
  versioned_docs/version-1.3/apis-clients/java-client/index.md
Labels: component:docs

#1276 docs(8.0): add using-templates changes
  versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/using-templates.md
Labels: component:docs

#1278 chore(guides): fix admonition whitespace
  docs/guides/getting-started-orchestrate-api-endpoints.md
  docs/guides/getting-started-orchestrate-human-tasks.md
  docs/guides/getting-started-orchestrate-microservices.md
Labels: kind/bug, component:docs

#1281 Howto updates
  README.md
  howtos/configuration.md
  howtos/documentation-guidelines.md
  howtos/markdown-and-mdx-features.md
  howtos/publish-documentation.md
  howtos/publish-documentation.svg
  howtos/release-procedure.md
  howtos/setup.md
  howtos/versioning.md
Labels: component:docs, dx

#1257 update community clients
  docs/apis-clients/community-clients/c-sharp.md
  docs/apis-clients/community-clients/javascript.md
  docs/apis-clients/community-clients/micronaut.md
  docs/apis-clients/community-clients/python.md
  docs/apis-clients/community-clients/ruby.md
  docs/apis-clients/community-clients/rust.md
Labels: component:docs

#1298 fix broken telemetry tables
  docs/self-managed/optimize-deployment/configuration/telemetry.md
  versioned_docs/version-1.3/self-managed/optimize-deployment/setup/telemetry.md
  versioned_docs/version-8.0/self-managed/optimize-deployment/configuration/telemetry.md
Labels: component:optimize

#1305 chore(docusaurus.config.js): cleanup, update main page
  docusaurus.config.js
Labels: component:docs, dx

#1255 feat(connectors): move to Connector SDK 0.2
  docs/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md
  docs/guides/update-guide/connectors/010-to-020.md
  docs/guides/update-guide/connectors/introduction.md
  docs/guides/update-guide/introduction.md
  sidebars.js
  versioned_docs/version-8.0/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md
  versioned_docs/version-8.0/guides/update-guide/connectors/010-to-020.md
  versioned_docs/version-8.0/guides/update-guide/connectors/introduction.md
  versioned_docs/version-8.0/guides/update-guide/introduction.md
  versioned_sidebars/version-8.0-sidebars.json
Labels: component:connectors

#1313 feat(docs): describe multi-instance docs in howto
  howtos/documentation-guidelines.md
  howtos/markdown-and-mdx-features.md
  howtos/versioning.md
Labels: kind/enhancement, component:docs, dx, epic:optimize-versions

#1318 docs(dependencies): fix Optimize BE mailto links
  docs/reference/dependencies.md
Labels: kind/bug, component:docs, component:optimize

#1321 Remove C8 stage publish workflow
  .github/workflows/publish-c8.yaml
Labels: dx

#1308 feat: add dependencies for Connectors
  docs/reference/dependencies.md
  versioned_docs/version-8.0/reference/dependencies.md
Labels: component:connectors

#1328 refactor: simplify version mapping logic
  src/mdx/expandVersionedUrl.js
  src/mdx/expandVersionedUrl.spec.js
Labels: component:docs, dx, epic:optimize-versions
