Repository camunda/camunda-docs, pull requests merged in 2022-04, with the labels that each got.

#721 Modeler renaming
  docs/components/modeler/about.md
  docs/components/modeler/bpmn/bpmn-coverage.md
  docs/components/modeler/bpmn/bpmn.md
  docs/components/modeler/bpmn/user-tasks/user-tasks.md
  docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md
  docs/components/modeler/desktop-modeler/element-templates/additional-resources.md
  docs/components/modeler/desktop-modeler/element-templates/configuring-templates.md
  docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
  docs/components/modeler/desktop-modeler/element-templates/using-templates.md
  docs/components/modeler/desktop-modeler/model-your-first-diagram.md
  docs/components/modeler/desktop-modeler/start-instance.md
  docs/components/modeler/desktop-modeler/telemetry/telemetry.md
  docs/components/modeler/web-modeler/collaboration.md
  docs/components/modeler/web-modeler/import-diagram.md
  docs/components/modeler/web-modeler/launch-cloud-modeler.md
  docs/components/modeler/web-modeler/milestones.md
  docs/components/modeler/web-modeler/model-your-first-diagram.md
  docs/components/modeler/web-modeler/new-web-modeler.md
  docs/components/modeler/web-modeler/save-and-deploy.md
  docs/components/modeler/web-modeler/start-instance.md
Labels: release/1.4.0

#733 Update licenses.md
  docs/reference/licenses.md
Labels: release/1.4.0

#763 Close ZeebeClient in example (closes https://github.com/camunda-cloud…
  docs/apis-clients/java-client/index.md
  versioned_docs/version-0.26/components/clients/java-client/get-started.md
Labels: release/1.4.0

#661 Document business rule task with called decision
  docs/components/concepts/incidents.md
  docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md
  docs/components/modeler/bpmn/manual-tasks/manual-tasks.md
  docs/components/modeler/bpmn/user-tasks/user-tasks.md
Labels: component/zeebe, component/modeler, release/1.4.0, component/documentation

#716 Document new DeployResource RPC and its usage
  docs/apis-clients/cli-client/get-started.md
  docs/apis-clients/cli-client/index.md
  docs/apis-clients/go-client/get-started.md
  docs/apis-clients/go-client/index.md
  docs/apis-clients/grpc.md
  docs/apis-clients/java-client-examples/process-deploy.md
  docs/apis-clients/java-client/zeebe-process-test.md
  docs/guides/utilizing-forms.md
  docs/reference/announcements.md
Labels: release/1.4.0

#706 getting started: clusters are no longer autocreated
  docs/guides/assets/react-components/create-cluster.md
  docs/guides/getting-started-orchestrate-human-tasks.md
  docs/guides/getting-started-orchestrate-microservices.md
  docs/guides/getting-started/create-camunda-cloud-account.md
  docs/guides/getting-started/create-your-cluster.md
  docs/guides/getting-started/img/home.png
  sidebars.js
Labels: hold

#777 docs(release-policy): updates for C8
  docs/reference/img/update-console.png
  docs/reference/release-policy.md
Labels: release/1.4.0

#790 docs(reference): renaming c8
  docs/reference/dependencies.md
  docs/reference/licenses.md
  docs/reference/overview.md
  docs/reference/status.md
Labels: release/1.4.0

#791 docs(pages): renaming c8
  src/pages/contact.md
  src/pages/index.js
  src/pages/meta.md
Labels: release/1.4.0

#792 docs(guides): renaming c8
  docs/guides/assets/react-components/create-cluster.md
  docs/guides/automating-a-process-using-bpmn.md
  docs/guides/getting-started-orchestrate-human-tasks.md
  docs/guides/getting-started-orchestrate-microservices.md
  docs/guides/getting-started/connect-to-your-cluster.md
  docs/guides/getting-started/create-camunda-cloud-account.md
  docs/guides/getting-started/deploy-your-process-and-start-process-instance.md
  docs/guides/getting-started/model-your-first-process.md
  docs/guides/getting-started/monitor-your-process-in-operate.md
  docs/guides/getting-started/setup-client-connection-credentials.md
  docs/guides/improve-processes-with-optimize.md
  docs/guides/introduction-to-camunda-cloud.md
  docs/guides/message-correlation.md
  docs/guides/operating-the-camunda-cloud-stack-on-kubernetes.md
  docs/guides/setting-up-development-project.md
  docs/guides/update-guide/introduction.md
  docs/guides/utilizing-forms.md
Labels: release/1.4.0

#833 chore(format): exclude build artifacts from prettier
  .github/workflows/publish-c8.yaml
  .prettierignore
Labels: dx

#810 feat(processes): document time goals feature
  docs/components/optimize/userguide/img/processes.png
  docs/components/optimize/userguide/img/set-owner.png
  docs/components/optimize/userguide/img/timeGoals.png
  docs/components/optimize/userguide/processes.md
  sidebars.js
Labels: component/optimize

#855 Broken links on latest
  docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
  docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
  docs/components/modeler/bpmn/bpmn-primer.md
  docs/guides/update-guide/introduction.md
  docs/self-managed/zeebe-deployment/configuration/configuration.md
Labels: kind/bug, component/docs

#824 docs(release-policy): split release policy
  docs/reference/release-policy.md
Labels: component/docs

#863 Feedback on backpressure pages
  docs/apis-clients/grpc.md
  docs/apis-clients/java-client/job-worker.md
  docs/components/zeebe/technical-concepts/internal-processing.md
  docs/self-managed/zeebe-deployment/operations/backpressure.md
  docs/self-managed/zeebe-deployment/operations/backups.md
  docs/self-managed/zeebe-deployment/operations/index.md
  docs/self-managed/zeebe-deployment/operations/metrics.md
  docs/self-managed/zeebe-deployment/operations/resource-planning.md
  static/.htaccess
Labels: component/docs

#866 revising alerts documentation
  docs/components/optimize/userguide/additional-features/alerts.md
Labels: component/docs, component/optimize
