Repository camunda/camunda-docs, pull requests merged in 2025-05, with the labels that each got.

#5633 feat: Add migration guide for decision requirements endpoints
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: deploy, low prio

#5473 Tasklist & Operate refresh_interval issue document
  versioned_docs/version-8.4/self-managed/operate-deployment/schema-and-migration.md
  versioned_docs/version-8.4/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.5/self-managed/operate-deployment/schema-and-migration.md
  versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/operate-deployment/schema-and-migration.md
  versioned_docs/version-8.7/self-managed/operate-deployment/schema-and-migration.md
Labels: low prio

#5673 fix: tls console
  docs/self-managed/console-deployment/configuration/ssl.md
  versioned_docs/version-8.7/self-managed/console-deployment/configuration/ssl.md
Labels: support, available & undocumented, 8.8.0-alpha3, 8.7.0

#5579 fix: update broken links in blue prism connector page
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/blueprism.md
Labels: component:connectors, low prio

#5593 move dependency maintenance policy
  docs/reference/announcements-release-notes/release-policy.md
  docs/reference/supported-environments.md
  src/css/custom.css
  versioned_docs/version-8.4/reference/release-policy.md
  versioned_docs/version-8.4/reference/supported-environments.md
  versioned_docs/version-8.5/reference/release-policy.md
  versioned_docs/version-8.5/reference/supported-environments.md
  versioned_docs/version-8.6/reference/announcements-release-notes/release-policy.md
  versioned_docs/version-8.6/reference/supported-environments.md
  versioned_docs/version-8.7/reference/announcements-release-notes/release-policy.md
  versioned_docs/version-8.7/reference/supported-environments.md
Labels: component:docs

#5669 docs: remove user search API
  api/camunda/version-8.6/camunda-openapi.yaml
  api/camunda/version-8.7/camunda-openapi.yaml
  static/.htaccess
  versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/find-all-users.api.mdx
  versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/sidebar.ts
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/find-all-users.api.mdx
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/sidebar.ts
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: kind/bug, support, target:8.6, target:8.7

#5672 fix: update camunda self-managed repos urls
  docs/components/modeler/web-modeler/play-your-process.md
  docs/guides/host-custom-connector.md
  versioned_docs/version-8.4/guides/host-custom-connector.md
  versioned_docs/version-8.5/guides/host-custom-connector.md
  versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md
  versioned_docs/version-8.6/guides/host-custom-connector.md
  versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
  versioned_docs/version-8.7/guides/host-custom-connector.md
Labels: component:self-managed, available & undocumented

#5678 feat: mention no proxy config in troubleshooting guide
  docs/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md
Labels: low prio

#5713 Port #5579 to 8.8 - Connector Blueprism docs
  docs/components/connectors/out-of-the-box-connectors/blueprism.md
Labels: component:connectors, low prio

#5621 Docs site styling and alignment with corporate sites
  docusaurus.config.js
  src/components/CamundaDistributions/index.jsx
  src/components/PageDescription.jsx
  src/css/custom.css
  src/theme/DocVersionBanner/index.tsx
  static/img/logo-camunda-black.svg
Labels: kind/enhancement, component:docs, deploy

#5704 Connector casing (wave 2 - components)
  docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
  docs/components/best-practices/development/routing-events-to-processes.md
  docs/components/camunda-integrations/overview.md
  docs/components/camunda-integrations/sap/camunda-sap-integration.md
  docs/components/camunda-integrations/sap/csap-cli.md
  docs/components/camunda-integrations/sap/odata-connector.md
  docs/components/camunda-integrations/sap/rfc-connector.md
  docs/components/concepts/clusters.md
  docs/components/concepts/document-handling.md
  docs/components/concepts/outbound-connectors-job-workers.md
  docs/components/concepts/what-is-camunda-8.md
  docs/components/console/manage-clusters/manage-secrets.md
  docs/components/modeler/about-modeler.md
  docs/components/modeler/desktop-modeler/element-templates/about-templates.md
  docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
  docs/components/modeler/desktop-modeler/flags/flags.md
  docs/components/modeler/desktop-modeler/use-connectors.md
  docs/components/modeler/web-modeler/advanced-modeling/refactoring-suggestions.md
  docs/components/modeler/web-modeler/camunda-marketplace.md
  docs/components/modeler/web-modeler/file-download.md
  docs/components/modeler/web-modeler/git-sync.md
  docs/components/modeler/web-modeler/play-your-process.md
  docs/components/react-components/connector-task.md
  docs/components/rpa/getting-started.md
  versioned_docs/version-8.7/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
  versioned_docs/version-8.7/components/best-practices/development/invoking-services-from-the-process-c7.md
  versioned_docs/version-8.7/components/best-practices/development/routing-events-to-processes-c7.md
  versioned_docs/version-8.7/components/best-practices/development/routing-events-to-processes.md
  versioned_docs/version-8.7/components/camunda-integrations/overview.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/camunda-sap-integration.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/csap-cli.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/odata-connector.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/rfc-connector.md
  versioned_docs/version-8.7/components/concepts/clusters.md
  versioned_docs/version-8.7/components/concepts/document-handling.md
  versioned_docs/version-8.7/components/concepts/outbound-connectors-job-workers.md
  versioned_docs/version-8.7/components/console/manage-clusters/manage-secrets.md
  versioned_docs/version-8.7/components/modeler/about-modeler.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/element-templates/about-templates.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/element-templates/defining-templates.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/flags/flags.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/use-connectors.md
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/refactoring-suggestions.md
  versioned_docs/version-8.7/components/modeler/web-modeler/camunda-marketplace.md
  versioned_docs/version-8.7/components/modeler/web-modeler/file-download.md
  versioned_docs/version-8.7/components/modeler/web-modeler/git-sync.md
  versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
  versioned_docs/version-8.7/components/react-components/connector-task.md
  versioned_docs/version-8.7/components/rpa/getting-started.md
Labels: component:docs, component:connectors, available & undocumented

#5708 Connector casing (wave 3 - guides)
  docs/guides/configuring-out-of-the-box-connector.md
  docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
  docs/guides/document-handling.md
  docs/guides/getting-started-orchestrate-apis.md
  docs/guides/host-custom-connector.md
  docs/guides/introduction-to-camunda-8.md
  docs/guides/migrating-from-camunda-7/conceptual-differences.md
  docs/guides/migrating-from-camunda-7/migration-journey.md
  docs/guides/migrating-from-camunda-7/technical-details.md
  docs/guides/use-connectors-in-hybrid-mode.md
  versioned_docs/version-8.7/guides/configuring-out-of-the-box-connector.md
  versioned_docs/version-8.7/guides/document-handling.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-apis.md
  versioned_docs/version-8.7/guides/host-custom-connector.md
  versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/conceptual-differences.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/technical-details.md
  versioned_docs/version-8.7/guides/use-connectors-in-hybrid-mode.md
Labels: component:docs, component:connectors, available & undocumented

#5710 Connector casing (wave 6 - API)
  docs/apis-tools/testing/connectors.md
  docs/apis-tools/testing/getting-started.md
  versioned_docs/version-8.7/apis-tools/testing/connectors.md
  versioned_docs/version-8.7/apis-tools/testing/getting-started.md
Labels: component:docs, component:connectors, available & undocumented

#5711 Connector casing (wave 5 - Self-Managed)
  docs/self-managed/concepts/document-handling/overview.md
  docs/self-managed/connectors-deployment/connectors-configuration.md
  docs/self-managed/connectors-deployment/install-and-start.md
  docs/self-managed/identity/user-guide/roles/manage-permissions.md
  docs/self-managed/operational-guides/update-guide/820-to-830.md
  docs/self-managed/operational-guides/update-guide/850-to-860.md
  docs/self-managed/operational-guides/update-guide/860-to-870.md
  docs/self-managed/reference-architecture/manual.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  docs/self-managed/setup/deploy/amazon/aws-ec2.md
  docs/self-managed/setup/deploy/local/c8run.md
  docs/self-managed/setup/deploy/local/docker-compose.md
  docs/self-managed/setup/deploy/local/manual.md
  docs/self-managed/setup/deploy/openshift/redhat-openshift.md
  docs/self-managed/setup/deploy/other/docker.md
  docs/self-managed/setup/guides/running-custom-connectors.md
  docs/self-managed/setup/guides/secret-management.md
  docs/self-managed/setup/install.md
  versioned_docs/version-8.7/self-managed/concepts/document-handling/overview.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/install-and-start.md
  versioned_docs/version-8.7/self-managed/identity/user-guide/roles/manage-permissions.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/820-to-830.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/docker-compose.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/manual.md
  versioned_docs/version-8.7/self-managed/setup/deploy/openshift/redhat-openshift.md
  versioned_docs/version-8.7/self-managed/setup/deploy/other/docker.md
  versioned_docs/version-8.7/self-managed/setup/guides/running-custom-connectors.md
  versioned_docs/version-8.7/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: component:docs, component:connectors, available & undocumented

#5636 C8 api intermediate tutorial
  docs/apis-tools/camunda-api-rest/intermediate-tutorial.md
  docs/apis-tools/camunda-api-rest/sidebar-schema.js
  docs/apis-tools/camunda-api-rest/tutorial.md
Labels: epic:api-interactivity, theme:api-streamline, component:api

#5651 Add documentation for new fromAi builtin FEEL function
  docs/components/modeler/feel/builtin-functions/feel-built-in-functions-introduction.md
  docs/components/modeler/feel/builtin-functions/feel-built-in-functions-miscellaneous.md
  docs/components/modeler/feel/sidebar-schema.js
Labels: 8.8.0-alpha4

#5725 docs: correct tasklist API deprecation note
  docs/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md
  versioned_docs/version-8.7/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md
Labels: kind/bug

#5712 Adjust top nav for 8.8
  docusaurus.config.js
Labels: dx, deploy, target:8.8, theme:restructure

#5722 retro review of console usage metrics
  docs/reference/data-collection/usage-metrics.md
  docs/self-managed/console-deployment/usage-metrics.md
  versioned_docs/version-8.5/self-managed/console-deployment/usage-metrics.md
  versioned_docs/version-8.6/reference/data-collection/usage-metrics.md
  versioned_docs/version-8.6/self-managed/console-deployment/usage-metrics.md
  versioned_docs/version-8.7/reference/data-collection/usage-metrics.md
  versioned_docs/version-8.7/self-managed/console-deployment/usage-metrics.md
Labels: component:console, component:self-managed

#5683 add diagnosis script
  docs/self-managed/operational-guides/troubleshooting/diagnostics.md
  sidebars.js
  versioned_docs/version-8.4/self-managed/platform-deployment/diagnostics.md
  versioned_docs/version-8.5/self-managed/operational-guides/troubleshooting/diagnostics.md
  versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/diagnostics.md
  versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/diagnostics.md
Labels: component:self-managed, deploy

#5721 Add Helm guide link to Connectors config
  docs/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
Labels: component:connectors, component:self-managed, low prio

#5659 API section restructure for 8.8
  docs/apis-tools/administration-api/sidebar-schema.js
  docs/apis-tools/camunda-api-rest/sidebar-schema.js
  docs/apis-tools/operate-api/sidebar-schema.js
  docs/apis-tools/tasklist-api-rest/sidebar-schema.js
  docs/apis-tools/web-modeler-api/sidebar-schema.js
  sidebars.js
Labels: component:docs, deploy, target:8.8

#5729 Update ad-hoc subprocess to ad-hoc sub-process
  docs/components/modeler/bpmn/ad-hoc-subprocesses/ad-hoc-subprocesses.md
  docs/components/modeler/bpmn/subprocesses.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  media-pre-src/docs/components/modeler/bpmn/ad-hoc/ad-hoc-subprocess-activate.bpmn
  media-pre-src/docs/components/modeler/bpmn/ad-hoc/ad-hoc-subprocess-demo.bpmn
  versioned_docs/version-8.7/components/modeler/bpmn/ad-hoc-subprocesses/ad-hoc-subprocesses.md
  versioned_docs/version-8.7/components/modeler/bpmn/subprocesses.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: kind/cleanup, component:docs, deploy

#5730 Landing page restructuring update
  src/pages/index.js
Labels: dx, deploy, target:8.8, theme:restructure

#5707 feat: Migration guide for variable endpoints
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: deploy, low prio

#5643 guide for external postgresql on self-managed Helm chart
  versioned_docs/version-8.5/self-managed/setup/guides/using-existing-postgres.md
  versioned_docs/version-8.6/self-managed/setup/guides/using-existing-postgres.md
  versioned_docs/version-8.7/self-managed/setup/guides/using-existing-postgres.md
  versioned_sidebars/version-8.5-sidebars.json
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:self-managed, target:8.5, 8.6.0, 8.7.0

#5738 Added link to API Mapping Guide
  docs/guides/migrating-from-camunda-7/code-conversion.md
  docs/guides/migrating-from-camunda-7/migration-tooling.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/code-conversion.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md
Labels: c7migration

#5736 Describe banned process instance concept
  docs/components/zeebe/technical-concepts/internal-processing.md
  versioned_docs/version-8.4/components/zeebe/technical-concepts/internal-processing.md
  versioned_docs/version-8.5/components/zeebe/technical-concepts/internal-processing.md
  versioned_docs/version-8.6/components/zeebe/technical-concepts/internal-processing.md
  versioned_docs/version-8.7/components/zeebe/technical-concepts/internal-processing.md
Labels: component:zeebe, available & undocumented

#5742 Fix hybrid connector docker env
  docs/guides/use-connectors-in-hybrid-mode.md
  src/components/PageDescription.jsx
  src/css/custom.css
  src/theme/DocVersionBanner/index.tsx
  versioned_docs/version-8.7/guides/use-connectors-in-hybrid-mode.md
Labels: kind/bug

#5709 Connector casing (wave 4 - reference)
  docs/reference/announcements-release-notes/850/850-announcements.md
  docs/reference/announcements-release-notes/850/850-release-notes.md
  docs/reference/announcements-release-notes/860/860-announcements.md
  docs/reference/announcements-release-notes/860/860-release-notes.md
  docs/reference/announcements-release-notes/870/870-announcements.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/announcements-release-notes/release-policy.md
  docs/reference/dependencies.md
  docs/reference/glossary.md
  docs/reference/licenses.md
  versioned_docs/version-8.7/reference/announcements-release-notes/850/850-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/850/850-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/860/860-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/860/860-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/release-policy.md
  versioned_docs/version-8.7/reference/dependencies.md
  versioned_docs/version-8.7/reference/glossary.md
  versioned_docs/version-8.7/reference/licenses.md
Labels: component:docs, component:connectors, available & undocumented

#5741 fix: add diagnistics script to sidebars
  versioned_sidebars/version-8.4-sidebars.json
  versioned_sidebars/version-8.5-sidebars.json
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: deploy

#5733 Update landing pages and menu
  docs/apis-tools/working-with-apis-tools.md
  docs/components/components-overview.md
  docs/guides/introduction-to-camunda-8.md
  docs/reference/overview.md
  docusaurus.config.js
  versioned_docs/version-8.4/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.4/components/components-overview.md
  versioned_docs/version-8.4/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.4/reference/overview.md
  versioned_docs/version-8.5/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.5/components/components-overview.md
  versioned_docs/version-8.5/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.5/reference/overview.md
  versioned_docs/version-8.6/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.6/components/components-overview.md
  versioned_docs/version-8.6/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.6/reference/overview.md
  versioned_docs/version-8.7/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.7/components/components-overview.md
  versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.7/reference/overview.md
Labels: dx, deploy, target:8.8, theme:restructure

#5734 Update configuration.md to help clarify how the 10MB limit works
  docs/components/concepts/document-handling.md
  docs/self-managed/concepts/document-handling/configuration.md
  versioned_docs/version-8.7/components/concepts/document-handling.md
  versioned_docs/version-8.7/self-managed/concepts/document-handling/configuration.md
Labels: low prio

#5662 Forward Identity SDK properties to 8.8
  docs/self-managed/identity/deployment/configuration-variables.md
Labels: component:identity, deploy, target:8.8, low prio

#5745 Add Desktop Modeler Settings doc
  docs/components/modeler/desktop-modeler/settings/img/settings.png
  docs/components/modeler/desktop-modeler/settings/settings.md
  sidebars.js
Labels: component:desktop-modeler, 8.8.0-alpha4

#5751 Remove business key target
  docs/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md
Labels: kind/bug

#5723 docs(email): make a correction, replaces header by key, was not conform to the reality
  docs/components/connectors/out-of-the-box-connectors/email.md
  versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/email.md
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/email.md
Labels: component:connectors, available & undocumented

#5754 Fix Roadmap URL in Migration Journey
  docs/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md
Labels: kind/bug, c7migration

#5638 8.8.0-Alpha4 Release Notes
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: component:docs, deploy, 8.8.0-alpha4

#5750 Update manual instructions to camunda/camunda for 8.6+
  docs/self-managed/setup/deploy/local/manual.md
  versioned_docs/version-8.6/self-managed/setup/deploy/local/manual.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/manual.md
Labels: kind/bug, component:self-managed, severity/low

#5677 docs: document intra cluster tls config
  docs/self-managed/operate-deployment/operate-configuration.md
  docs/self-managed/tasklist-deployment/tasklist-configuration.md
  docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md
  versioned_docs/version-8.6/self-managed/operate-deployment/operate-configuration.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/security/secure-cluster-communication.md
  versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/security/secure-cluster-communication.md
Labels: component:zeebe, component:operate, component:tasklist, component:self-managed

#5739 Remove 8.3 from supported env and update guides
  docs/reference/announcements-release-notes/850/850-announcements.md
  docs/reference/supported-environments.md
  docs/self-managed/operational-guides/update-guide/820-to-830.md
  docs/self-managed/operational-guides/update-guide/introduction.md
  sidebars.js
  static/.htaccess
  versioned_docs/version-8.7/reference/announcements-release-notes/850/850-announcements.md
  versioned_docs/version-8.7/reference/supported-environments.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/820-to-830.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/introduction.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:docs, low prio

#5671 Add new configs to Azure backup configuration.
  docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
Labels: component:self-managed

#5766 Add 8.8.0-alpha4 blog
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: component:docs, 8.8.0-alpha4

#5632 fix: Improve docs on shard and replica configuration
  docs/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.4/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
Labels: target:8.4, target:8.6, target:8.7, deploy, target:8.5, target:8.8

#5746 fix: Improve the API migration guide
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: deploy, low prio

#5789 fix: remove unreleased `is blank` feel function
  versioned_docs/version-8.7/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md
Labels: kind/bug, support

#5780 Spring SDK, document tenantId config semantics.
  docs/apis-tools/spring-zeebe-sdk/configuration.md
Labels: 8.8.0-alpha5

#5787 Top nav CSS for smaller screens
  src/css/custom.css
Labels: component:docs, dx, deploy

#5726 docs: added vector DB support
  docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md
  sidebars.js
Labels: deploy, target:8.8, 8.8.0-alpha5

#5794 fix: corrected document handling link
  docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md
Labels: kind/bug

#5802 fix: use app token instead of PAT
  .github/workflows/add-to-project.yaml
Labels: dx

#5795 Fix API request endpoint
  docs/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/optimize-backup.md
Labels: kind/bug, component:optimize

#4704 add clarification to elasticsearch privileges
  docs/self-managed/concepts/elasticsearch-privileges.md
  versioned_docs/version-8.4/self-managed/concepts/elasticsearch-privileges.md
  versioned_docs/version-8.5/self-managed/concepts/elasticsearch-privileges.md
  versioned_docs/version-8.6/self-managed/concepts/elasticsearch-privileges.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.7/self-managed/concepts/elasticsearch-privileges.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup-and-restore.md
Labels: component:self-managed

#5800 fix: Remove unneeded `move-to-done` workflow
  .github/workflows/move-to-done.yaml
Labels: dx

#5792 docs: document messageBatch option in elasticsearch and opensearch ex…
  docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
  versioned_docs/version-8.4/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.4/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
  versioned_docs/version-8.5/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.5/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
Labels: low prio, available & undocumented

#5832 fix(web-modeler): correct description for cluster scope config
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md
Labels: kind/bug, component:web-modeler-sm

#5833 docs(web-modeler): clarify usage of CLIENT_CREDENTIALS cluster auth
  docs/reference/announcements-release-notes/870/870-announcements.md
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
  versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md
Labels: kind/bug, component:web-modeler-sm

#5840 Remove scenarios limitation for SM
  docs/components/modeler/web-modeler/play-your-process.md
Labels: available & undocumented

#5642 feat: port identity alternative-database docs to 8.7
  versioned_docs/version-8.7/self-managed/identity/user-guide/configuration/alternative-db.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:identity, component:self-managed

#5849 docs(web-modeler): notice for CVE-2025-23166
  docs/reference/notices.md
  versioned_docs/version-8.4/reference/notices.md
  versioned_docs/version-8.5/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: kind/bug, component:web-modeler-SaaS, component:web-modeler-sm

#5847 deps: drop `replace-in-file` in favor of plain `fs`
  api/camunda/generation-strategy.js
  api/make-server-dynamic.js
  api/remove-duplicate-version-badge.js
  api/tasklist/generation-strategy.js
  api/zeebe/generation-strategy.js
  package-lock.json
  package.json
Labels: dx

#5858 docs: document broken upgrade version for tasklist
  docs/self-managed/operational-guides/update-guide/830-to-840.md
  docs/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.4/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.5/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/840-to-850.md
Labels: support

#5801 adjust connectors config instructions
  docs/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
Labels: component:connectors, component:self-managed

#5860 Update Algolia key
  docusaurus.config.js
Labels: dx, deploy

#5554 Clarify RAFT committing and explain example replication factors
  docs/components/zeebe/technical-concepts/clustering.md
  versioned_docs/version-8.6/components/zeebe/technical-concepts/clustering.md
  versioned_docs/version-8.7/components/zeebe/technical-concepts/clustering.md
Labels: deploy, available & undocumented

#5768 Rework for #4601
  docs/self-managed/about-self-managed.md
  docs/self-managed/get-started/index.md
  docs/self-managed/setup/install.md
  docs/self-managed/setup/overview.md
  docs/self-managed/setup/upgrade.md
  docs/self-managed/update/index.md
  sidebars.js
Labels: component:self-managed, deploy, low prio

#5851 feat(rest-connector): Add hint about multipart/form-data
  docs/components/connectors/protocol/rest.md
  versioned_docs/version-8.7/components/connectors/protocol/rest.md
Labels: low prio

#5865 fix: remove duplicate enterprise license secret in secret guide
  docs/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.6/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.7/self-managed/setup/guides/secret-management.md
Labels: deploy

#5836 fix: drop unneeded docusaurus v1 package
  package-lock.json
  package.json
Labels: dx, deploy

#5888 link to modes from token sim
  docs/components/modeler/web-modeler/token-simulation.md
  versioned_docs/version-8.7/components/modeler/web-modeler/token-simulation.md
Labels: component:modeler

#5731 doc handling phases 2 and 3
  docs/components/document-handling/display-and-download-document.md
  docs/components/document-handling/upload-document-to-bpmn-process.md
  docs/guides/utilizing-forms.md
  versioned_docs/version-8.7/components/document-handling/display-and-download-document.md
  versioned_docs/version-8.7/components/document-handling/upload-document-to-bpmn-process.md
  versioned_docs/version-8.7/guides/utilizing-forms.md
Labels: component:docs

#5868 Remove akeller from documentation-guidelines.md
  howtos/documentation-guidelines.md
Labels: dx, low prio

#4580 Add C8 REST guidelines
  docs/apis-tools/camunda-api-rest/camunda-api-rest-authentication.md
  docs/apis-tools/camunda-api-rest/camunda-api-rest-data-fetching.md
  docs/apis-tools/camunda-api-rest/camunda-api-rest-overview.md
  docs/apis-tools/camunda-api-rest/sidebar-schema.js
Labels: component:zeebe, theme:api-streamline, deploy

#5883 docs(utilities): mocking utilities for CPT
  docs/apis-tools/testing/utilities.md
Labels: deploy

#5718 docs(ootbc): update mapping rules docs
  docs/self-managed/concepts/mapping-rules.md
  docs/self-managed/identity/orchestration-identity/img/authorizations-mapping-rule-tab.png
  docs/self-managed/identity/orchestration-identity/img/create-mapping-rule-authorization-modal.png
  docs/self-managed/identity/orchestration-identity/img/delete-mapping-rule.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-add-mapping-modal.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-add-mapping.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-delete-modal.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-edit-icon.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-edit-modal.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-management-tab.png
  docs/self-managed/identity/orchestration-identity/img/mapping-rule-refreshed-table.png
  docs/self-managed/identity/orchestration-identity/img/remove-tenant-mapping.png
  docs/self-managed/identity/orchestration-identity/img/tenant-assign-mapping-modal-empty.png
  docs/self-managed/identity/orchestration-identity/img/tenant-assign-mapping-modal-selected.png
  docs/self-managed/identity/orchestration-identity/img/tenant-detail-mappings-empty.png
  docs/self-managed/identity/orchestration-identity/img/tenant-mapping-assigned.png
  docs/self-managed/identity/orchestration-identity/img/tenant-mapping-list.png
  docs/self-managed/identity/orchestration-identity/mapping-rules/assign-mappings-to-tenants.md
  docs/self-managed/identity/orchestration-identity/mapping-rules/managing-mapping-rules.md
  docs/self-managed/identity/orchestration-identity/mapping-rules/mapping-rules-authorizations.md
  docs/self-managed/identity/user-guide/img/mapping-rule-add-mapping-modal.png
  docs/self-managed/identity/user-guide/img/mapping-rule-delete-modal.png
  docs/self-managed/identity/user-guide/img/mapping-rule-management-tab.png
  docs/self-managed/identity/user-guide/img/mapping-rule-refreshed-table.png
  docs/self-managed/identity/user-guide/mapping-rules/managing-mapping-rules.md
  sidebars.js
  static/.htaccess
Labels: target:8.8

#5799 tidy install desktop modeler page
  docs/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/install-the-modeler.md
Labels: component:desktop-modeler

#5892 chore: add version description field to the release announcement
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, 8.8.0-alpha4

#5272 Change migration specifics from Camunda 7 description to Camunda 8 description
  docs/components/best-practices/operations/versioning-process-definitions.md
  versioned_docs/version-8.6/components/best-practices/operations/versioning-process-definitions.md
  versioned_docs/version-8.7/components/best-practices/operations/versioning-process-definitions.md
Labels: low prio

#5897 Remove limitation for 8.7 and 8.8
  docs/reference/regions.md
  versioned_docs/version-8.7/reference/regions.md
Labels: available & undocumented

#5886 chore(docs): document how use gitsync with an azure repository
  docs/components/modeler/web-modeler/git-sync.md
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, 8.8.0-alpha5
