Repository camunda/camunda-docs, pull requests merged in 2025-06, with the labels that each got.

#5782 docs(agentic-ai): Add initial docs for AI Agent connectors
  docs/components/connectors/img/agenticai-ad-hoc-sub-process-multi-instance.png
  docs/components/connectors/img/agenticai-ai-agent-loop-overview.png
  docs/components/connectors/img/agenticai-tool-resolution-fromAi.png
  docs/components/connectors/img/agenticai-tool-resolution.png
  docs/components/connectors/img/agenticai-tools-loop-empty.png
  docs/components/connectors/img/agenticai-user-feedback-loop.png
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-ahsp-tools-schema-resolver.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-example.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
  docs/components/modeler/feel/builtin-functions/feel-built-in-functions-miscellaneous.md
  sidebars.js
Labels: deploy, 8.8.0-alpha5

#5907 docs(play): remove scenarios SaaS-only badge
  versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
Labels: low prio

#5908 Fix versions typo in release notes
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: low prio

#5909 Update install.md
  docs/self-managed/setup/install.md
Labels: available & undocumented

#5767 fix: restore procedure does not cover deletion of zeebe data
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup-and-restore.md
Labels: kind/bug

#5913 fix admonition bug for open ai connector
  docs/components/connectors/out-of-the-box-connectors/openai.md
  versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/openai.md
  versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/openai.md
  versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/openai.md
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/openai.md
Labels: kind/bug, component:connectors

#5895 Rename and improve sm getstarted and install section
  docs/self-managed/get-started/index.md
  docs/self-managed/run-locally/index.md
  docs/self-managed/setup/overview.md
  sidebars.js
Labels: deploy

#5790 Document `creating` and `canceling` user task listeners
  docs/components/concepts/user-task-listeners.md
  docs/self-managed/operational-guides/update-guide/870-to-880.md
Labels: deploy

#5923 fix: update helm-chart-production-guide.md link
  versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
Labels: low prio

#5920 docs(glossary): introduce element template to glossary
  docs/reference/glossary.md
  versioned_docs/version-8.4/reference/glossary.md
  versioned_docs/version-8.5/reference/glossary.md
  versioned_docs/version-8.6/reference/glossary.md
  versioned_docs/version-8.7/reference/glossary.md
Labels: low prio

#5930 docs: extend update guide with OpenAPI changes
  docs/self-managed/operational-guides/update-guide/860-to-870.md
  docs/self-managed/operational-guides/update-guide/870-to-880.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
Labels: low prio, component:api, 8.8.0

#5617 FEEL Playground documentation
  docs/components/modeler/feel/assets/feel-playground-example-error-json.png
  docs/components/modeler/feel/assets/feel-playground-example-invalid-expression.png
  docs/components/modeler/feel/assets/feel-playground-example-warning-json.png
  docs/components/modeler/feel/assets/feel-playground-example.png
  docs/components/modeler/feel/assets/feel-playground-open.png
  docs/components/modeler/feel/assets/feel-playground-validation-approved.png
  docs/components/modeler/feel/assets/feel-playground-validation-error.png
  docs/components/modeler/feel/assets/feel-playground-validation-warning.png
  docs/components/modeler/feel/feel-playground.md
  docs/components/modeler/feel/sidebar-schema.js
  src/css/custom.css
Labels: component:modeler, component:web-modeler-SaaS, deploy, target:8.8, 8.8.0-alpha5

#5936 fix(available-connectors-overview): fix marketplace spelling
  docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
  sidebars.js
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: low prio

#5933 Add glossary navigation
  docs/reference/glossary.md
  src/css/custom.css
Labels: component:docs, deploy, low prio

#5919 Agentic orchestration
  docs/components/agentic-orchestration/agentic-orchestration.md
  docs/components/agentic-orchestration/ai-agents.md
  docs/components/agentic-orchestration/design-architecture.md
  docs/components/agentic-orchestration/img/ao-ai-agent.png
  docs/components/agentic-orchestration/img/ao-example-integration.png
  docs/components/agentic-orchestration/img/ao-overview-hero.png
  docs/components/agentic-orchestration/img/ao-workflow.png
  sidebars.js
  src/css/custom.css
Labels: component:docs, component:connectors, deploy, target:8.8, 8.8.0-alpha5

#5781 docs(desktop-modeler): add `zeebe:userTask` binding
  docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
Labels: component:desktop-modeler, 8.8.0-alpha5

#5929 add links to related academy courses for guides
  docs/components/document-handling/send-document-to-external-system.md
  docs/components/react-components/create-cluster.md
  docs/guides/automating-a-process-using-bpmn.md
  docs/guides/configuring-out-of-the-box-connector.md
  docs/guides/create-account.md
  docs/guides/create-decision-tables-using-dmn.md
  docs/guides/getting-started-java-spring.md
  docs/guides/getting-started-orchestrate-apis.md
  docs/guides/getting-started-orchestrate-microservices.md
  docs/guides/host-custom-connector.md
  docs/guides/improve-processes-with-optimize.md
  docs/guides/introduction-to-camunda-8.md
  docs/guides/migrating-from-camunda-7/index.md
  docs/guides/model-your-first-process.md
  docs/guides/setup-client-connection-credentials.md
  docs/guides/utilizing-forms.md
  versioned_docs/version-8.7/components/document-handling/send-document-to-external-system.md
  versioned_docs/version-8.7/components/react-components/create-cluster.md
  versioned_docs/version-8.7/guides/automating-a-process-using-bpmn.md
  versioned_docs/version-8.7/guides/configuring-out-of-the-box-connector.md
  versioned_docs/version-8.7/guides/create-account.md
  versioned_docs/version-8.7/guides/create-decision-tables-using-dmn.md
  versioned_docs/version-8.7/guides/getting-started-java-spring.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-apis.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-microservices.md
  versioned_docs/version-8.7/guides/host-custom-connector.md
  versioned_docs/version-8.7/guides/improve-processes-with-optimize.md
  versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/index.md
  versioned_docs/version-8.7/guides/model-your-first-process.md
  versioned_docs/version-8.7/guides/setup-client-connection-credentials.md
  versioned_docs/version-8.7/guides/utilizing-forms.md
Labels: component:docs

#5916 docs(self-managed): remove unnedded *.migration.env values
  docs/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.5/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.6/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.7/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
Labels: support, component:self-managed, 8.8.0-alpha5

#5954 Announcements admonitions
  docs/reference/announcements-release-notes/850/850-announcements.md
  docs/reference/announcements-release-notes/850/850-release-notes.md
  docs/reference/announcements-release-notes/860/860-announcements.md
  docs/reference/announcements-release-notes/870/870-announcements.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  versioned_docs/version-8.6/reference/announcements-release-notes/850/850-announcements.md
  versioned_docs/version-8.6/reference/announcements-release-notes/850/850-release-notes.md
  versioned_docs/version-8.6/reference/announcements-release-notes/860/860-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/850/850-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/850/850-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/860/860-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
Labels: component:docs, deploy

#5902 SAP improvements
  docs/components/camunda-integrations/sap/btp-plugin.md
  docs/components/camunda-integrations/sap/camunda-sap-integration.md
  docs/components/camunda-integrations/sap/csap-cli.md
  docs/components/camunda-integrations/sap/img/sap-odata-connector-element-template-advanced.png
  docs/components/camunda-integrations/sap/img/sap-odata-connector-task-error-handling2.png
  docs/components/camunda-integrations/sap/img/sap-odata-connector-task-in-model.png
  docs/components/camunda-integrations/sap/img/sap-odata-connector-template.png
  docs/components/camunda-integrations/sap/img/sap-rfc-connector-task-in-model.png
  docs/components/camunda-integrations/sap/odata-connector.md
  docs/components/camunda-integrations/sap/rfc-connector.md
  docs/components/connectors/img/connector-sap-odata.png
  docs/components/connectors/img/connector-sap-rfc.png
  docs/components/connectors/react-components/_connectors-table.js
  docs/components/modeler/forms/camunda-forms-reference.md
  docs/reference/glossary.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/btp-plugin.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/camunda-sap-integration.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/csap-cli.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-btp-plugin-model-user-task.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-odata-connector-element-template-advanced.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-odata-connector-task-error-handling2.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-odata-connector-task-in-model.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-odata-connector-template.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/img/sap-rfc-connector-task-in-model.png
  versioned_docs/version-8.7/components/camunda-integrations/sap/odata-connector.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/rfc-connector.md
  versioned_docs/version-8.7/components/connectors/img/connector-sap-odata.png
  versioned_docs/version-8.7/components/connectors/img/connector-sap-rfc.png
  versioned_docs/version-8.7/components/connectors/react-components/_connectors-table.js
  versioned_docs/version-8.7/components/modeler/forms/camunda-forms-reference.md
  versioned_docs/version-8.7/reference/glossary.md
Labels: component:docs

#5948 backport connectors sdk type and property
  docs/components/connectors/custom-built-connectors/connector-sdk.md
  versioned_docs/version-8.4/components/connectors/custom-built-connectors/connector-sdk.md
  versioned_docs/version-8.5/components/connectors/custom-built-connectors/connector-sdk.md
  versioned_docs/version-8.6/components/connectors/custom-built-connectors/connector-sdk.md
Labels: component:connectors

#5960 Add custom exporter section
  versioned_docs/version-8.7/self-managed/concepts/exporters.md
Labels: support, component:self-managed, deploy

#5967 fix: Update installation instructions for CSAP CLI
  docs/components/camunda-integrations/sap/csap-cli.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/csap-cli.md
Labels: available & undocumented, 8.7.0

#5978 Update featured connectors for alpha-5
  docs/components/connectors/img/connector-aiagent.png
  docs/components/connectors/img/connector-vector.png
  docs/components/connectors/react-components/_connectors-card-data.js
  docs/components/connectors/react-components/_connectors-table.js
Labels: component:docs, component:connectors, deploy, available & undocumented

#5974 feat(connectors): Adding docs for new azure blob storage connector
  docs/components/connectors/img/connector-azure-blob-storage.png
  docs/components/connectors/out-of-the-box-connectors/azure-blob-storage.md
  docs/components/connectors/react-components/_connectors-table.js
  sidebars.js
Labels: 8.8.0-alpha7

#5999 docs(web-modeler): security notice 21
  docs/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: kind/bug, component:web-modeler-sm

#6003 docs: adjust API DTO names in update guide
  docs/self-managed/operational-guides/update-guide/870-to-880.md
Labels: low prio

#6009 docs(feel-playground): remove pre-filled
  docs/components/modeler/feel/feel-playground.md
Labels: low prio

#5976 feat(webmodeler): document how to setup gitsync with bitbucket
  docs/components/modeler/web-modeler/git-sync.md
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, 8.8.0-alpha6

#5995 Update 8.7 exporter docs
  versioned_docs/version-8.7/self-managed/concepts/exporters.md
Labels: 8.7.4

#6018 adjust references of wrench in modeler
  docs/components/camunda-integrations/sap/odata-connector.md
  docs/components/camunda-integrations/sap/rfc-connector.md
  docs/components/modeler/bpmn/bpmn.md
  docs/components/modeler/bpmn/undefined-tasks/undefined-tasks.mdx
  docs/components/modeler/desktop-modeler/model-your-first-diagram.md
  docs/components/modeler/dmn/dmn.md
  docs/components/modeler/web-modeler/run-or-publish-your-process.md
  docs/guides/automating-a-process-using-bpmn.md
  docs/guides/getting-started-java-spring.md
  docs/guides/getting-started-orchestrate-apis.md
  docs/guides/getting-started-orchestrate-human-tasks.md
  docs/guides/getting-started-orchestrate-microservices.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/odata-connector.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/rfc-connector.md
  versioned_docs/version-8.7/components/modeler/bpmn/bpmn.md
  versioned_docs/version-8.7/components/modeler/bpmn/undefined-tasks/undefined-tasks.mdx
  versioned_docs/version-8.7/components/modeler/desktop-modeler/model-your-first-diagram.md
  versioned_docs/version-8.7/components/modeler/dmn/dmn.md
  versioned_docs/version-8.7/components/modeler/web-modeler/run-or-publish-your-process.md
  versioned_docs/version-8.7/guides/automating-a-process-using-bpmn.md
  versioned_docs/version-8.7/guides/getting-started-java-spring.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-apis.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-human-tasks.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-microservices.md
Labels: component:modeler, component:web-modeler-SaaS

#5970 update sm reference architecture section
  docs/self-managed/setup/deploy/amazon/aws-marketplace.md
  sidebars.js
  static/.htaccess
Labels: component:self-managed, deploy

#6002 [CPT] I can read how to connect to a remote runtime
  docs/apis-tools/testing/configuration.md
  docs/apis-tools/testing/getting-started.md
  sidebars.js
Labels: target:8.8

#6037 feat(desktop-modeler): hint on desktop modeler <> IDE interplay
  docs/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/index.md
Labels: component:desktop-modeler

#5943 refactor: add performance best practices section
  docs/components/best-practices/development/writing-good-workers.md
Labels: deploy

#5942 AI Agent: add documentation for structured outputs/JSON mode
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
Labels: deploy, 8.8.0-alpha6, agentic orchestration

#6049 docs: Update 880-announcements.md to reflect client method rename
  docs/reference/announcements-release-notes/880/880-announcements.md
Labels: 8.8.0

#6013 Add docs for Groups and Roles
  docs/components/identity/authorization.md
  docs/components/identity/group.md
  docs/components/identity/img/create-group-tab.png
  docs/components/identity/img/create-role-tab.png
  docs/components/identity/img/update-group-tab.png
  docs/components/identity/role.md
  sidebars.js
Labels: deploy

#6053 feat: c8run startup url parameter docs
  docs/self-managed/setup/deploy/local/c8run.md
Labels: 8.8.0-alpha6
