Repository camunda/camunda-docs, pull requests merged in 2025-10, with the labels that each got.

#6905 docs: refactor orchestration properties page to be inline with spring client page
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/properties.md
Labels: 8.8.0

#6921 docs(reference): add agentic orchestration
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
Labels: deploy, 8.8.0

#6923 docs(self-managed): add detailed helm upgrade secrets extraction
  docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
Labels: component:self-managed, self-managed:helm

#6935 docs(self-managed): update ingress and port-forward instructions
  docs/components/connectors/custom-built-connectors/host-custom-connector.md
  docs/self-managed/deployment/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
  docs/self-managed/deployment/helm/cloud-providers/azure/microsoft-aks/aks-helm.md
  docs/self-managed/deployment/helm/configure/accessing-components-without-ingress.md
  docs/self-managed/deployment/helm/configure/authentication-and-authorization.md
  docs/self-managed/deployment/helm/configure/ingress-setup.md
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
Labels: component:self-managed, self-managed:helm

#6927 docs(migration): add release notes for migration improvements for 8.8
  docs/reference/announcements-release-notes/880/880-release-notes.md
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
Labels: 8.8.0

#6960 Update what's new in 8.8
  docs/apis-tools/migration-manuals/index.md
  docs/components/whats-new-in-88.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
  docs/self-managed/update/administrators/overview.md
Labels: component:docs, 8.8.0

#6961 Update Algolia search
  versioned_docs/version-8.7/components/concepts/process-applications.md
Labels: kind/bug

#6967 chore (self-managed): remove multi namespace guide
  docs/self-managed/deployment/helm/configure/multi-namespace-deployment.md
  docs/self-managed/deployment/helm/install/production/index.md
  docs/self-managed/reference-architecture/kubernetes.md
  sidebars.js
  static/.htaccess
  versioned_docs/version-8.5/self-managed/setup/guides/multi-namespace-deployment.md
  versioned_docs/version-8.6/self-managed/setup/guides/multi-namespace-deployment.md
  versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
  versioned_docs/version-8.7/self-managed/reference-architecture/kubernetes.md
  versioned_docs/version-8.7/self-managed/setup/guides/multi-namespace-deployment.md
  versioned_sidebars/version-8.5-sidebars.json
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:self-managed, deploy, 8.8.0

#6979 fix(release-notes): Merged duplicated release not on orchestration cluster
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: component:zeebe, 8.8.0

#6968 docs(data-migrator): parallel gateway limitation
  docs/guides/migrating-from-camunda-7/data-migrator/limitations.md
Labels: 8.8.0

#6978 Agentic AI/MCP/fromAi adaptions
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-task-example.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-tool-definitions.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
  docs/components/early-access/alpha/mcp-client/mcp-client-connector.md
  docs/components/modeler/feel/builtin-functions/feel-built-in-functions-miscellaneous.md
Labels: 8.8.0, agentic orchestration

#6689 feat: add security notice for CVE-2025-58056
  docs/reference/notices.md
  versioned_docs/version-8.5/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: 8.8.0

#6944 Update agentic orchestration overview
  docs/components/agentic-orchestration/agentic-orchestration.md
  docs/components/agentic-orchestration/ai-agents.md
  docs/components/agentic-orchestration/design-architecture.md
  docs/components/agentic-orchestration/img/ao-overview-hero.png
  docs/components/assets/icon-play.png
  docs/components/react-components/_ao-card-data.js
  docs/components/react-components/_ao-card.js
  docs/components/react-components/_ao-table.css
Labels: deploy, 8.8.0, agentic orchestration

#6359 docs: s3 legacy md5 plugin support
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/broker.md
  docs/self-managed/operational-guides/troubleshooting.md
  versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/troubleshooting.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md
  versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/broker.md
Labels: deploy

#6901 docs: update whats new/upgrade guide to note tenant interceptor changes
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
  docs/self-managed/update/administrators/prepare-for-update.md
Labels: 8.8.0

#6989 fix: correct architecture diagram by remove console array to db
  docs/self-managed/deployment/helm/install/production/img/architecture.png
Labels: target:8.8

#6994 docs(web-modeler): document changes in cluster configuration in 8.8
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
  docs/self-managed/components/components-upgrade/870-to-880.md
  docs/self-managed/components/modeler/web-modeler/configuration/configuration.md
  docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider.md
Labels: component:web-modeler-sm, 8.8.0
