Repository camunda/camunda-docs, pull requests merged in 2025-08, with the labels that each got.

#6329 Add Camunda Exporter back into sidebar
  sidebars.js
Labels: kind/bug, component:self-managed, 8.8.0

#6323 add notes for multi tenancy
  docs/self-managed/installation-methods/helm/configure/configure-multi-tenancy.md
  versioned_docs/version-8.5/self-managed/operational-guides/configure-multi-tenancy.md
  versioned_docs/version-8.6/self-managed/operational-guides/configure-multi-tenancy.md
  versioned_docs/version-8.7/self-managed/operational-guides/configure-multi-tenancy.md
Labels: component:self-managed

#6333 Update architecture diagram
  docs/guides/img/c8-architecture-diagram.png
Labels: deploy, available & undocumented

#6346 Update what's new in 88
  docs/apis-tools/migration-manuals/index.md
  docs/components/whats-new-in-88.md
Labels: 8.8.0

#6343 docs: announce deprecation of Web Modeler API milestone endpoints
  docs/reference/announcements-release-notes/880/880-announcements.md
Labels: 8.8.0-alpha7

#6350 fix(reference): identity supports more databases
  versioned_docs/version-8.7/reference/supported-environments.md
Labels: low prio

#6306 feat: runtime instructions in the CreateProcessInstance RPC
  docs/apis-tools/zeebe-api/gateway-service.md
Labels: 8.8.0-alpha7

#6348 chore(deps): new renovate rules to increment automerge rate
  .github/renovate.json5
Labels: low prio

#6264 fix sm landing page cards
  src/components/CamundaSelfManaged/Components.jsx
Labels: component:self-managed, deploy

#6360 [CPT] Add new assertions and utilities
  docs/apis-tools/testing/assertions.md
  docs/apis-tools/testing/getting-started.md
  docs/apis-tools/testing/utilities.md
Labels: deploy

#6371 docs(exporter): lowercase camunda exporter id in the documentation
  docs/self-managed/components/orchestration-cluster/zeebe/exporters/camunda-exporter.md
Labels: 8.8.0-alpha7

#6356 docs(web-modeler): GitHub Enterprise support for SaaS
  docs/components/modeler/web-modeler/git-sync.md
Labels: component:web-modeler-SaaS, available & undocumented

#6293 IDP structured extraction
  docs/components/modeler/web-modeler/idp/idp-document-extraction.md
  docs/components/modeler/web-modeler/idp/idp-reference.md
  docs/components/modeler/web-modeler/idp/idp-structured-extraction.md
  docs/components/modeler/web-modeler/idp/img/extracted-fields-and-tables-configure-tables.png
  docs/components/modeler/web-modeler/idp/img/extracted-fields-and-tables-configure.png
  docs/components/modeler/web-modeler/idp/img/extracted-fields-and-tables.png
  docs/components/modeler/web-modeler/idp/img/idp-create-extraction-project-modal.png
  docs/components/modeler/web-modeler/idp/img/idp-extracted-test-template.png
  docs/components/modeler/web-modeler/idp/img/idp-publish-structured.png
  docs/components/modeler/web-modeler/idp/img/idp-structured-instructions-upload.png
  docs/components/modeler/web-modeler/idp/img/idp-test-template-view-extraction.png
  docs/components/modeler/web-modeler/idp/img/idp-upload-test-template-empty.png
  docs/components/modeler/web-modeler/idp/img/idp-upload-test-template.png
  sidebars.js
Labels: deploy, 8.8.0-alpha7

#6069 docs: ec2 small rework
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md
Labels: component:self-managed, component:infex, deploy, target:8.8

#6383 Add initial benefits summary to What's new in Camunda 8.8
  docs/components/whats-new-in-88.md
Labels: component:docs, deploy, 8.8.0

#6302 docs(gdrive): Add a note about shared drives specifics
  docs/components/connectors/out-of-the-box-connectors/googledrive.md
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/googledrive.md
Labels: target:8.7, 8.8.0-alpha7

#6402 Backport hostnames and ip addresses
  versioned_docs/version-8.5/reference/ip-addresses.md
  versioned_docs/version-8.6/reference/ip-addresses.md
  versioned_docs/version-8.7/reference/ip-addresses.md
  versioned_sidebars/version-8.5-sidebars.json
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:docs, deploy, available & undocumented

#6382 small clarification and changes
  versioned_docs/version-8.5/self-managed/setup/install.md
  versioned_docs/version-8.6/self-managed/setup/install.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: deploy

#6336 add note on ilm for data retention
  docs/self-managed/components/orchestration-cluster/operate/data-retention.md
  versioned_docs/version-8.5/self-managed/operate-deployment/data-retention.md
  versioned_docs/version-8.6/self-managed/operate-deployment/data-retention.md
  versioned_docs/version-8.7/self-managed/operate-deployment/data-retention.md
Labels: component:operate, component:docs

#6374 880-alpha7 release notes
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: 8.8.0-alpha7

#6407 88 alpha7 release notes fixes
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: 8.8.0-alpha7

#6392 docs(migration): add migration guidelines for camunda java client
  docs/apis-tools/migration-manuals/index.md
  docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
  sidebars.js
Labels: deploy, 8.8.0

#6408 docs: small ec2 folder rename to procedure
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md
Labels: component:self-managed, component:infex

#6325 docs(self-managed): no secondary storage support
  docs/self-managed/concepts/no-secondary-storage.md
  sidebars.js
Labels: deploy, 8.8.0-alpha8

#6372 Align REST API schema naming
  api/camunda/camunda-openapi.yaml
Labels: 8.8.0-alpha8

#6412 docs(self-managed): Minor fixes for typos and wording
  versioned_docs/version-8.5/self-managed/setup/install.md
  versioned_docs/version-8.6/self-managed/setup/install.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: low prio

#6106 feat: rename zeebe to orchestration cluster
  docs/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md
Labels: component:desktop-modeler

#6388 Document vector database new providers
  docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md
Labels: deploy, agentic orchestration, 8.8.0-alpha8

#6415 fix: readd content that was removed by rebases and remove content tha…
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/broker.md
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
  docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
Labels: kind/bug, deploy, target:8.8

#6426 fix: change usage metric auth resource to permission
  docs/components/concepts/access-control/authorizations.md
Labels: 8.8.0-alpha8

#6429 adjusting admin api sidebar
  docs/apis-tools/administration-api/sidebar-schema.js
Labels: component:api

#5969 feat: added secure headers config
  docs/self-managed/components/orchestration-cluster/identity/configuration.md
Labels: component:identity, 8.8.0

#6209 docs: added csrf protection doc
  docs/self-managed/components/orchestration-cluster/identity/configuration.md
Labels: component:identity, target:8.8, 8.8.0-alpha8

#6422 Rename authorization resource type "application" to "component"
  docs/components/concepts/access-control/authorizations.md
Labels: deploy, low prio

#6438 docs(web-modeler): backport non-public database schema support to 8.6
  versioned_docs/version-8.4/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.5/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/database.md
Labels: component:web-modeler-sm, 8.8.0-alpha8

#6434 fix: broken link reference in ec2
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md
Labels: component:self-managed, component:infex

#6420 fix(idp-configuration): Add instructions for identity-enabled clusters in idp
  docs/components/modeler/web-modeler/idp/idp-configuration.md
Labels: 8.8.0-alpha8

#6386 initial guide oidc orchestration cluster
  docs/components/concepts/access-control/connect-to-identity-provider.md
  docs/components/console/manage-organization/external-sso.md
  docs/self-managed/components/management-identity/configuration/connect-to-an-oidc-provider.md
  docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider.md
  sidebars.js
Labels: deploy, 8.8.0

#6395 Remove gifs
  docs/components/modeler/bpmn/assets/modeler.gif
  docs/components/modeler/bpmn/assets/sub-process.gif
  docs/components/modeler/bpmn/bpmn-primer.md
  docs/components/modeler/dmn/assets/desktop-modeler-dmn/demo.gif
  docs/components/modeler/dmn/dmn.md
  docs/components/modeler/web-modeler/collaboration.md
  docs/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.gif
  docs/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.png
  docs/components/modeler/web-modeler/img/token-simulation/play.gif
  docs/components/modeler/web-modeler/img/token-simulation/speed.gif
  docs/components/modeler/web-modeler/img/token-simulation/start.gif
  docs/components/modeler/web-modeler/img/token-simulation/toggle.gif
  docs/components/modeler/web-modeler/token-simulation.md
  versioned_docs/version-8.5/components/modeler/bpmn/assets/modeler.gif
  versioned_docs/version-8.5/components/modeler/bpmn/assets/sub-process.gif
  versioned_docs/version-8.5/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.5/components/modeler/dmn/assets/desktop-modeler-dmn/demo.gif
  versioned_docs/version-8.5/components/modeler/dmn/dmn.md
  versioned_docs/version-8.5/components/modeler/web-modeler/collaboration.md
  versioned_docs/version-8.5/components/modeler/web-modeler/img/attention-grabber-pointer-pulse copy.png
  versioned_docs/version-8.5/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.gif
  versioned_docs/version-8.5/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.png
  versioned_docs/version-8.5/components/modeler/web-modeler/img/token-simulation/play.gif
  versioned_docs/version-8.5/components/modeler/web-modeler/img/token-simulation/speed.gif
  versioned_docs/version-8.5/components/modeler/web-modeler/img/token-simulation/start.gif
  versioned_docs/version-8.5/components/modeler/web-modeler/img/token-simulation/toggle.gif
  versioned_docs/version-8.5/components/modeler/web-modeler/token-simulation.md
  versioned_docs/version-8.6/components/modeler/bpmn/assets/modeler.gif
  versioned_docs/version-8.6/components/modeler/bpmn/assets/sub-process.gif
  versioned_docs/version-8.6/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.6/components/modeler/dmn/dmn.md
  versioned_docs/version-8.6/components/modeler/web-modeler/collaboration.md
  versioned_docs/version-8.6/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.gif
  versioned_docs/version-8.6/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.png
  versioned_docs/version-8.6/components/modeler/web-modeler/img/token-simulation/play.gif
  versioned_docs/version-8.6/components/modeler/web-modeler/img/token-simulation/speed.gif
  versioned_docs/version-8.6/components/modeler/web-modeler/img/token-simulation/start.gif
  versioned_docs/version-8.6/components/modeler/web-modeler/img/token-simulation/toggle.gif
  versioned_docs/version-8.6/components/modeler/web-modeler/token-simulation.md
  versioned_docs/version-8.7/components/modeler/bpmn/assets/modeler.gif
  versioned_docs/version-8.7/components/modeler/bpmn/assets/sub-process.gif
  versioned_docs/version-8.7/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.7/components/modeler/dmn/assets/desktop-modeler-dmn/demo.gif
  versioned_docs/version-8.7/components/modeler/dmn/dmn.md
  versioned_docs/version-8.7/components/modeler/web-modeler/collaboration.md
  versioned_docs/version-8.7/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.gif
  versioned_docs/version-8.7/components/modeler/web-modeler/img/attention-grabber-pointer-pulse.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/token-simulation/play.gif
  versioned_docs/version-8.7/components/modeler/web-modeler/img/token-simulation/speed.gif
  versioned_docs/version-8.7/components/modeler/web-modeler/img/token-simulation/start.gif
  versioned_docs/version-8.7/components/modeler/web-modeler/img/token-simulation/toggle.gif
  versioned_docs/version-8.7/components/modeler/web-modeler/token-simulation.md
Labels: component:docs

#6464 feat: add new ILM policy config for usage metrics in Camunda Exporter
  docs/components/concepts/data-retention.md
  docs/self-managed/components/orchestration-cluster/zeebe/exporters/camunda-exporter.md
Labels: 8.8.0

#6449 docs: remove variable rollover configuration
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/self-managed/components/optimize/configuration/service-config.yaml
  docs/self-managed/components/optimize/configuration/system-configuration.md
Labels: 8.8.0

#6486 docs(Self-managed): Fix typos
  docs/self-managed/operational-guides/backup-restore/restore.md
  docs/self-managed/operational-guides/monitoring/log-levels.md
  docs/self-managed/operational-guides/monitoring/metrics.md
  docs/self-managed/operational-guides/troubleshooting.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/deploy.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/restore.md
Labels: kind/bug, component:docs

#6489 docs(self-managed): Fix docs link typo
  docs/self-managed/update/administrators/run-update.md
Labels: kind/bug, 8.8.0

#6313 update secret management
  docs/self-managed/installation-methods/helm/configure/secret-management.md
  versioned_docs/version-8.7/self-managed/setup/guides/secret-management.md
Labels: kind/bug, component:self-managed

#6481 chore: add note about speeding up restore
  docs/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/restore.md
Labels: component:self-managed

#6403 docs(identity): add documentation and troubleshooting info for basic authentication (#39392)
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-authentication.md
  docs/self-managed/operational-guides/troubleshooting.md
Labels: 8.8.0

#6451 docs(api): swagger support for 8.8
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-overview.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-swagger.md
  docs/apis-tools/orchestration-cluster-api-rest/react-components/_api-card-data.js
  docs/apis-tools/orchestration-cluster-api-rest/react-components/_api-card.css
  docs/apis-tools/orchestration-cluster-api-rest/react-components/_api-card.js
  docs/apis-tools/orchestration-cluster-api-rest/react-components/img/interactive-api-explorer-icon.png
  docs/apis-tools/orchestration-cluster-api-rest/react-components/img/openapi-icon.png
  docs/apis-tools/orchestration-cluster-api-rest/react-components/img/postman-icon.png
  docs/apis-tools/orchestration-cluster-api-rest/react-components/img/swagger-icon.png
  docs/apis-tools/orchestration-cluster-api-rest/sidebar-schema.js
Labels: deploy, 8.8.0-alpha8

#6506 ci: adapt sync-rest-api-docs to renaming
  api/camunda/generation-strategy.js
Labels: kind/bug, 8.8.0-alpha8

#6487 docs: add more changed client methods
  docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
  docs/reference/announcements-release-notes/880/880-announcements.md
Labels: 8.8.0-alpha8

#6469 docs(config): document index template priority configuration in 8.7
  versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
Labels: target:8.7, 8.7.11

#6513 feat: support enhanced specification for 8.8
  .github/workflows/sync-rest-api-docs.yaml
  api/camunda/generation-strategy-8.8.js
  api/camunda/generation-strategy-legacy.js
  api/camunda/generation-strategy.js
  src/mdx/MarkerEventuallyConsistentExtension.js
  src/mdx/MarkerStronglyConsistentExtension.js
Labels: dx, available & undocumented

#6501 docs(save-as-element-template): document "save as" for tasks
  docs/components/modeler/web-modeler/img/save-as-template/1-business-rule-task.png
  docs/components/modeler/web-modeler/img/save-as-template/2-save-as-template-button.png
  docs/components/modeler/web-modeler/img/save-as-template/3-template-saved.png
  docs/components/modeler/web-modeler/img/save-as-template/4-edit-template.png
  docs/components/modeler/web-modeler/img/save-as-template/5-finalized-template.png
  docs/components/modeler/web-modeler/img/save-as-template/6-publish-template.png
  docs/components/modeler/web-modeler/img/save-as-template/7-apply-template.png
  docs/components/modeler/web-modeler/save-as-element-templates.md
  sidebars.js
Labels: deploy, 8.8.0-alpha8

#6414 Phase 1 & 2: Orchestration cluster core settings and features
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-swagger.md
  docs/components/connectors/out-of-the-box-connectors/csv.md
  docs/components/modeler/bpmn/user-tasks/user-tasks.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/self-managed/components/management-identity/miscellaneous/configuration-variables.md
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/csrf-protection.md
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/licensing.md
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/logging.md
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/properties.md
  docs/self-managed/components/orchestration-cluster/core-settings/configuration/webserver.md
  docs/self-managed/components/orchestration-cluster/core-settings/overview.md
  docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider.md
  docs/self-managed/components/orchestration-cluster/identity/overview.md
  docs/self-managed/components/orchestration-cluster/operate/operate-configuration.md
  docs/self-managed/components/orchestration-cluster/tasklist/tasklist-configuration.md
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/configuration.md
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/logging.md
  docs/self-managed/installation-methods/manual/install.md
  docs/self-managed/operational-guides/monitoring/log-levels.md
  sidebars.js
  static/.htaccess
Labels: component:self-managed, deploy, target:8.8, 8.8.0

#6531 chore: misc changes around ec2 and others
  docs/self-managed/installation-methods/manual/cloud-providers/amazon/aws-ec2.md
  docs/self-managed/installation-methods/manual/install.md
  docs/self-managed/operational-guides/backup-restore/restore.md
Labels: component:self-managed

#6542 Revert "docs(web-modeler): backport non-public database schema suppor…
  versioned_docs/version-8.4/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.5/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/database.md
Labels: component:web-modeler-sm, 8.8.0-alpha8

#6519 6475 enhance the user guides for orchestration cluster identity
  docs/components/concepts/access-control/authorizations.md
  docs/components/identity/authorization.md
  docs/components/identity/client.md
  docs/components/identity/group.md
  docs/components/identity/identity-introduction.md
  docs/components/identity/img/update-group-tab.png
  docs/components/identity/role.md
  docs/components/identity/user.md
  sidebars.js
Labels: component:identity, deploy, target:8.8, 8.8.0

#6484 (docs): Java Client improvements
  docs/apis-tools/java-client-examples/cluster-topology-request.md
  docs/apis-tools/java-client-examples/data-pojo.md
  docs/apis-tools/java-client-examples/decision-evaluate.md
  docs/apis-tools/java-client-examples/index.md
  docs/apis-tools/java-client-examples/job-worker-open.md
  docs/apis-tools/java-client-examples/process-deploy.md
  docs/apis-tools/java-client-examples/process-instance-cancel-batch.md
  docs/apis-tools/java-client-examples/process-instance-create-nonblocking.md
  docs/apis-tools/java-client-examples/process-instance-create-with-result.md
  docs/apis-tools/java-client-examples/process-instance-create.md
  docs/apis-tools/java-client/authentication.md
  docs/apis-tools/java-client/getting-started.md
  docs/apis-tools/java-client/index.md
  docs/apis-tools/java-client/job-worker.md
  docs/apis-tools/migration-manuals/index.md
  docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
  docs/apis-tools/migration-manuals/migrate-to-camunda-process-test.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-authentication.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-data-fetching.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-overview.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-swagger.md
  docs/apis-tools/orchestration-cluster-api-rest/sidebar-schema.js
  docs/apis-tools/spring-zeebe-sdk/configuration.md
  docs/apis-tools/testing/getting-started.md
  docs/apis-tools/testing/zeebe-process-test.md
  docs/apis-tools/working-with-apis-tools.md
  docs/apis-tools/zeebe-api/gateway-service.md
  docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
  docs/components/concepts/execution-listeners.md
  docs/components/concepts/user-task-listeners.md
  docs/components/connectors/custom-built-connectors/connector-sdk.md
  docs/components/modeler/web-modeler/integrate-web-modeler-in-ci-cd.md
  docs/components/whats-new-in-88.md
  docs/components/zeebe/technical-concepts/batch-operations.md
  docs/components/zeebe/technical-concepts/protocols.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/public-api.md
  docs/self-managed/components/modeler/web-modeler/configuration/configuration.md
  docs/self-managed/components/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
  docs/self-managed/quickstart/developer-quickstart/c8run.md
  sidebars.js
Labels: deploy

#6510 docs(self-managed): add notes for upgrade
  docs/self-managed/installation-methods/helm/upgrade/helm-820-830.md
  docs/self-managed/installation-methods/helm/upgrade/helm-830-840.md
  docs/self-managed/installation-methods/helm/upgrade/helm-840-850.md
  docs/self-managed/installation-methods/helm/upgrade/helm-850-860.md
  docs/self-managed/installation-methods/helm/upgrade/helm-860-870.md
  docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
  docs/self-managed/installation-methods/helm/upgrade/index.md
  docs/self-managed/update/administrators/overview.md
  src/components/CamundaDistributions/Helm.jsx
  src/components/CamundaDistributions/index.jsx
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md
  versioned_docs/version-8.5/self-managed/setup/upgrade.md
  versioned_docs/version-8.6/self-managed/setup/upgrade.md
  versioned_docs/version-8.7/self-managed/setup/upgrade.md
Labels: component:self-managed, severity/high

#6508 chore(modeler-interop): document interoperability between desktop and web modeler
  docs/components/modeler/using-web-and-desktop-modeler-together.md
  sidebars.js
Labels: component:web-modeler-SaaS, component:desktop-modeler, deploy, 8.8.0-alpha8

#6547 docs(config): document index template priority in 8.8
  docs/self-managed/components/orchestration-cluster/operate/operate-configuration.md
  docs/self-managed/components/orchestration-cluster/tasklist/tasklist-configuration.md
Labels: 8.8.0-alpha8

#6452 docs(migration): add migration guide for spring boot camunda starter
  docs/apis-tools/migration-manuals/index.md
  docs/apis-tools/migration-manuals/migrate-to-spring-boot-camunda-starter.md
  sidebars.js
Labels: deploy, 8.8.0
