Repository camunda/camunda-docs, pull requests merged in 2025-07, with the labels that each got.

#5981 Correct rollover interval description.
  docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md
Labels: low prio

#6014 feat(rpa): expand production documentation
  docs/components/rpa/img/architecture-overview.png
  docs/components/rpa/production.md
  versioned_docs/version-8.7/components/rpa/img/architecture-overview.png
  versioned_docs/version-8.7/components/rpa/production.md
Labels: deploy, low prio

#5934 docs(connectors): add the new GetJson intrinsic function documentation
  docs/components/connectors/use-connectors/intrinsic-functions.md
  versioned_docs/version-8.7/components/connectors/use-connectors/intrinsic-functions.md
Labels: 8.8.0-alpha6, 8.7.4

#5979 GitHub connector: Create or upload file content
  docs/components/connectors/out-of-the-box-connectors/github.md
Labels: component:connectors, 8.8.0-alpha6

#6090 Fix admonitions
  docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
Labels: component:modeler

#6097 docs(glossary): add reference architecture
  docs/reference/glossary.md
Labels: low prio

#6093 doc(helm): enterprise images vendor
  docs/self-managed/setup/install.md
  versioned_docs/version-8.5/self-managed/setup/install.md
  versioned_docs/version-8.6/self-managed/setup/install.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: deploy, 8.8.0-alpha6

#6044 Document processing metrics availability
  docs/self-managed/operational-guides/monitoring/metrics.md
  versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/metrics.md
  versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/metrics.md
  versioned_docs/version-8.6/self-managed/operational-guides/monitoring/metrics.md
  versioned_docs/version-8.7/self-managed/operational-guides/monitoring/metrics.md
Labels: available & undocumented

#6061 Feat-new-getting-started-experience
  docs/guides/getting-started-example.md
  docs/guides/getting-started-java-spring.md
  docs/guides/img/get-started-example-deploy.png
  docs/guides/img/get-started-example-output-java.png
  docs/guides/img/get-started-example-start-process.png
  docs/guides/img/getting-started-example-output.png
  docs/guides/img/getting-started-guide-example-process.png
  sidebars.js
Labels: deploy

#6115 Update regions map
  docs/reference/img/diagram-regions-map.png
  versioned_docs/version-8.4/reference/img/diagram-regions-map.png
  versioned_docs/version-8.5/reference/img/diagram-regions-map.png
  versioned_docs/version-8.6/reference/img/diagram-regions-map.png
  versioned_docs/version-8.7/reference/img/diagram-regions-map.png
Labels: kind/bug, component:docs

#6124 docs: backup and restore 8.6 port
  static/.htaccess
  versioned_docs/version-8.6/reference/glossary.md
  versioned_docs/version-8.6/self-managed/concepts/elasticsearch-without-cluster-privileges.md
  versioned_docs/version-8.6/self-managed/operate-deployment/operate-configuration.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/assets/icon-backup.png
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/assets/icon-prereqs.png
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/assets/icon-restore.png
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/modeler-backup-and-restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/react-components/_card-data.js
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md
  versioned_sidebars/version-8.6-sidebars.json
Labels: component:self-managed, deploy

#6112 docs: add Operate screenshot
  docs/guides/getting-started-example.md
  docs/guides/img/get-started-operate-screenshot.png
Labels: available & undocumented

#6161 Fix Getting Started Guide Windows stop command
  docs/guides/getting-started-example.md
Labels: kind/bug

#6023 1039 kafka connector update connector properties and docs
  docs/components/connectors/out-of-the-box-connectors/kafka.md
Labels: component:connectors

#6168 ci: adapt sync-rest-api-docs to renaming
  api/camunda/generation-strategy.js
Labels: kind/bug

#6149 feat(self-managed): new index page
  docs/self-managed/about-self-managed.md
  src/components/CamundaDistributions/C8Run.jsx
  src/components/CamundaDistributions/DockerCompose.jsx
  src/components/CamundaDistributions/Helm.jsx
  src/components/CamundaSelfManaged/CamundaSelfManaged.jsx
  src/components/CamundaSelfManaged/Components.jsx
  src/components/CamundaSelfManaged/Infrastructure.jsx
  src/components/CamundaSelfManaged/Installation.jsx
  src/components/CamundaSelfManaged/Introduction.jsx
  src/components/CamundaSelfManaged/QuickStart.jsx
  src/components/CamundaSelfManaged/ReferenceArchitecture.jsx
  src/components/CamundaSelfManaged/icons/aws.svg
  src/components/CamundaSelfManaged/icons/azure.svg
  src/components/CamundaSelfManaged/icons/cluster-management.svg
  src/components/CamundaSelfManaged/icons/cluster-orchestration.svg
  src/components/CamundaSelfManaged/icons/docker.svg
  src/components/CamundaSelfManaged/icons/gcp.svg
  src/components/CamundaSelfManaged/icons/jar.svg
  src/components/CamundaSelfManaged/icons/kubernetes.svg
  src/components/CamundaSelfManaged/icons/openshift.svg
  src/components/CamundaSelfManaged/icons/user-administrator.svg
  src/components/CamundaSelfManaged/icons/user-developer.svg
  src/components/CamundaSelfManaged/index.jsx
  src/components/CamundaSelfManaged/styles.css
  src/components/Versions.jsx
Labels: kind/enhancement, component:self-managed, deploy

#6175 incorporate immis sm comments
  src/components/CamundaSelfManaged/Introduction.jsx
Labels: component:self-managed

#6158 docs(element-templates): add documentation for `script` binding
  docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
Labels: deploy, available & undocumented

#6186 fix: update link to Bernd's "Lost in transaction" talk
  docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
  versioned_docs/version-8.4/components/best-practices/development/dealing-with-problems-and-exceptions.md
  versioned_docs/version-8.5/components/best-practices/development/dealing-with-problems-and-exceptions.md
  versioned_docs/version-8.6/components/best-practices/development/dealing-with-problems-and-exceptions.md
  versioned_docs/version-8.7/components/best-practices/development/dealing-with-problems-and-exceptions.md
Labels: kind/bug

#6207 docs: backup and restore further adjustments
  docs/self-managed/operational-guides/backup-restore/backup.md
  docs/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/restore.md
Labels: component:self-managed, low prio

#6199 feat: introduce tenant-aware connector secrets
  docs/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
Labels: component:connectors

#6190 fix: update the title page to what is actually there
  spec/regression/smoke.spec.ts
Labels: low prio

#6143 feat: update Java client authentication
  docs/apis-tools/java-client/authentication.md
  versioned_docs/version-8.6/apis-tools/java-client/index.md
  versioned_docs/version-8.7/apis-tools/java-client/index.md
Labels: affects/8.7, affects/8.6

#6079 Agentic AI: Documentation for experimental MCP client integration
  docs/components/agentic-orchestration/ai-agents.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
  docs/components/early-access/alpha/mcp-client/img/mcp-client-hitl.png
  docs/components/early-access/alpha/mcp-client/img/mcp-clients-architecture.png
  docs/components/early-access/alpha/mcp-client/mcp-client-connector.md
  docs/components/early-access/alpha/mcp-client/mcp-client.md
  docs/components/early-access/alpha/mcp-client/mcp-remote-client-connector.md
  sidebars.js
Labels: deploy, 8.8.0-alpha7

#6051 Update workshop link
  docs/guides/migrating-from-camunda-7/migration-journey.md
Labels: low prio

#6172 Agentic AI: improve documentation for agent context variable naming
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
Labels: deploy, available & undocumented, agentic orchestration

#6210 docs: update `CamundaClient` examples and JobResult gRPC docs
  docs/apis-tools/zeebe-api/gateway-service.md
  docs/components/concepts/job-workers.md
  docs/components/concepts/user-task-listeners.md
Labels: 8.8.0-alpha6

#6074 docs: correct PI search API migration
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: low prio, component:api

#6206 Guide for Self-Managed update to 8.8 with focus on admin and developer personas
  docs/apis-tools/migration-manuals/index.md
  docs/components/whats-new-in-88.md
  docs/self-managed/update/administrators/prepare-for-update.md
  docs/self-managed/update/administrators/run-update.md
  docs/self-managed/update/index.md
  sidebars.js
Labels: component:self-managed, deploy, target:8.8

#6173 Agentic AI: Add documentation on customization/custom storage support
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-customization.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
  sidebars.js
Labels: deploy, 8.8.0-alpha7, agentic orchestration

#6245 fix(connectors): Fix type of webhook connector
  docs/components/connectors/react-components/_connectors-table.js
  versioned_docs/version-8.7/components/connectors/react-components/_connectors-table.js
Labels: kind/bug

#6217 Improvements to the user task listener documentation
  docs/components/concepts/user-task-listeners.md
  docs/components/modeler/bpmn/user-tasks/user-tasks.md
Labels: 8.8.0-alpha7

#6229 Add Camunda console ping configs.
  docs/self-managed/console-deployment/configuration/configuration.md
Labels: 8.8.0

#6226 identity migration doc for 8.8 Phase 2
  docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
Labels: 8.8.0-alpha7

#6129 docs: document zeebe batch operation
  docs/apis-tools/java-client-examples/index.md
  docs/apis-tools/java-client-examples/process-instance-cancel-batch.md
  docs/components/zeebe/technical-concepts/assets/batch-operation.png
  docs/components/zeebe/technical-concepts/batch-operations.md
  docs/components/zeebe/technical-concepts/technical-concepts-overview.md
  docs/self-managed/identity/access-management/resource-authorizations.md
  docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md
  sidebars.js
Labels: 8.8.0-alpha7

#6251 Improve authorizations based on feedback
  docs/components/concepts/access-control/authorizations.md
  docs/components/concepts/resource-authorizations.md
  docs/components/console/manage-clusters/settings.md
  docs/components/identity/authorization.md
  docs/components/modeler/web-modeler/integrate-web-modeler-in-ci-cd.md
  docs/components/modeler/web-modeler/run-or-publish-your-process.md
  docs/components/tasklist/userguide/starting-processes.md
  docs/self-managed/identity/access-management/access-management-overview.md
  docs/self-managed/identity/access-management/resource-authorizations.md
  docs/self-managed/identity/miscellaneous/configuration-variables.md
  docs/self-managed/operate-deployment/operate-authentication.md
  docs/self-managed/orchestration-identity/installation.md
  docs/self-managed/tasklist-deployment/tasklist-authentication.md
  sidebars.js
Labels: deploy

#6208 update identity config first tweaks
  docs/reference/supported-environments.md
  docs/self-managed/orchestration-identity/configuration.md
Labels: deploy

#6241 Improve and update the API docs UX
  docs/apis-tools/java-client/authentication.md
  docs/apis-tools/java-client/index.md
  docs/apis-tools/java-client/zeebe-process-test.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-authentication.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-data-fetching.md
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-overview.md
  docs/apis-tools/working-with-apis-tools.md
  docs/reference/public-api.md
  docs/self-managed/orchestration-cluster/orchestration-cluster-api-rest-deployment-configuration.md
  docs/self-managed/quickstart/developer-quickstart/c8run.md
  docs/self-managed/quickstart/developer-quickstart/docker-compose.md
  sidebars.js
Labels: deploy, available & undocumented

#6254 docs: fix input mappings
  docs/components/concepts/variables.md
  versioned_docs/version-8.5/components/concepts/variables.md
  versioned_docs/version-8.6/components/concepts/variables.md
  versioned_docs/version-8.7/components/concepts/variables.md
Labels: kind/bug, available & undocumented

#6181 add note on issue with multi tenancy and zeebe
  docs/self-managed/installation-methods/helm/configure/configure-multi-tenancy.md
  versioned_docs/version-8.5/self-managed/operational-guides/configure-multi-tenancy.md
  versioned_docs/version-8.6/self-managed/operational-guides/configure-multi-tenancy.md
  versioned_docs/version-8.7/self-managed/operational-guides/configure-multi-tenancy.md
Labels: component:identity, component:self-managed

#6242 docs(connectors): update page on managing connector templates in Web Modeler
  docs/components/connectors/custom-built-connectors/connector-templates.md
  docs/components/connectors/img/connector-templates/connector-template-editor.png
  docs/components/connectors/img/connector-templates/create-connector-template-1.png
  docs/components/connectors/img/connector-templates/create-connector-template-2.png
  docs/components/connectors/img/connector-templates/create-connector-template-3.png
  docs/components/connectors/img/connector-templates/edit-connector-template-1.png
  docs/components/connectors/img/connector-templates/edit-connector-template-2.png
  docs/components/connectors/img/connector-templates/edit-connector-template-3.png
  docs/components/connectors/img/connector-templates/fix-connector-template-problems-1.png
  docs/components/connectors/img/connector-templates/fix-connector-template-problems-2.png
  docs/components/connectors/img/connector-templates/fix-connector-template-problems.png
  docs/components/connectors/img/connector-templates/manage-connector-templates-no-org-privileges.png
  docs/components/connectors/img/connector-templates/manage-connector-templates-org-privileges.png
  docs/components/connectors/img/connector-templates/publish-to-organization-from-editor.png
  docs/components/connectors/img/connector-templates/publish-to-organization-from-versions-list.png
  docs/components/connectors/img/connector-templates/publish-version-to-project.png
  docs/components/connectors/img/connector-templates/replace-via-upload.png
  docs/components/connectors/img/connector-templates/upload-files.png
  docs/components/connectors/manage-connector-templates.md
Labels: 8.8.0-alpha7

#6102 update 8.7 install link
  versioned_docs/version-8.5/self-managed/setup/install.md
  versioned_docs/version-8.6/self-managed/setup/install.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: component:self-managed

#6237 fix(irsa): include notice about opensearch read replicas
  docs/self-managed/installation-methods/helm/configure/database/all-shards-failed.md
  sidebars.js
Labels: component:self-managed, deploy, 8.8.0

#6041 docs: standalone schema and backup managers docs
  docs/self-managed/concepts/elasticsearch-without-cluster-privileges.md
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
  sidebars.js
  versioned_docs/version-8.6/self-managed/concepts/elasticsearch-without-cluster-privileges.md
  versioned_docs/version-8.7/self-managed/concepts/elasticsearch-without-cluster-privileges.md
Labels: 8.8.0-alpha7

#6294 chore(deps): migrate to react-player v3
  docs/components/modeler/bpmn/bpmn-primer.md
  howtos/markdown-and-mdx-features.md
  package-lock.json
  package.json
  versioned_docs/version-8.4/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.5/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.6/components/modeler/bpmn/bpmn-primer.md
  versioned_docs/version-8.7/components/modeler/bpmn/bpmn-primer.md
Labels: deploy

#6297 update academy links
  docs/components/modeler/bpmn/automating-a-process-using-bpmn.md
  docs/components/modeler/web-modeler/model-your-first-diagram.md
  versioned_docs/version-8.7/guides/automating-a-process-using-bpmn.md
  versioned_docs/version-8.7/guides/getting-started-orchestrate-microservices.md
  versioned_docs/version-8.7/guides/model-your-first-process.md
Labels: component:docs, low prio

#6298 fix: implement QA feedback in getting-started-example
  docs/guides/getting-started-example.md
Labels: kind/bug

#6305 Update snapshot references
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-customization.md
  docs/self-managed/components/orchestration-cluster/zeebe/operations/cluster-scaling.md
  docs/self-managed/concepts/elasticsearch-without-cluster-privileges.md
Labels: kind/bug, component:docs

#6307 What's new in 8.8 base content
  docs/components/assets/orchestration-cluster.png
  docs/components/whats-new-in-88.md
Labels: deploy, available & undocumented, 8.8.0

#6300 feat: Notice for CVE-2025-52520
  docs/reference/notices.md
Labels: support

#6316 feat: Notice for CVE-2025-52520 [backport]
  versioned_docs/version-8.5/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: support
