Repository camunda/camunda-docs, pull requests merged in 2025-09, with the labels that each got.

#6556 Update user guides for mapping rules - Orchestration Cluster Identity
  docs/components/concepts/access-control/mapping-rules.md
  docs/components/identity/authorization.md
  docs/components/identity/group.md
  docs/components/identity/img/authorizations-mapping-rule-tab.png
  docs/components/identity/img/create-mapping-rule-authorization-modal.png
  docs/components/identity/img/delete-mapping-rule.png
  docs/components/identity/img/mapping-rule-add-mapping-modal.png
  docs/components/identity/img/mapping-rule-add-mapping.png
  docs/components/identity/img/mapping-rule-delete-modal.png
  docs/components/identity/img/mapping-rule-edit-icon.png
  docs/components/identity/img/mapping-rule-edit-modal.png
  docs/components/identity/img/mapping-rule-management-tab.png
  docs/components/identity/img/mapping-rule-refreshed-table.png
  docs/components/identity/img/tenant-assign-mapping-rule-modal-empty.png
  docs/components/identity/img/tenant-assign-mapping-rule-modal-selected.png
  docs/components/identity/img/tenant-detail-mapping-rules-empty.png
  docs/components/identity/img/tenant-list.png
  docs/components/identity/img/tenant-mapping-rule-assigned.png
  docs/components/identity/mapping-rules/assign-mapping-rules-to-tenants.md
  docs/components/identity/mapping-rules/manage-mapping-rules.md
  docs/components/identity/mapping-rules/mapping-rules-authorizations.md
  docs/components/identity/role.md
  docs/reference/announcements-release-notes/850/850-release-notes.md
  docs/self-managed/components/console/overview.md
  docs/self-managed/components/orchestration-cluster/identity/img/authorizations-mapping-rule-tab.png
  docs/self-managed/components/orchestration-cluster/identity/img/create-mapping-rule-authorization-modal.png
  docs/self-managed/components/orchestration-cluster/identity/img/delete-mapping-rule.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-add-mapping-modal.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-delete-modal.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-edit-icon.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-edit-modal.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-management-tab.png
  docs/self-managed/components/orchestration-cluster/identity/img/mapping-rule-refreshed-table.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-assign-mapping-rule-modal-empty.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-assign-mapping-rule-modal-selected.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-detail-mapping-rules-empty.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-list.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-mapping-rule-assigned.png
  docs/self-managed/components/orchestration-cluster/identity/img/tenant-remove-mapping-rule.png
  docs/self-managed/components/orchestration-cluster/identity/overview.md
  docs/self-managed/concepts/mapping-rules.md
  sidebars.js
  static/.htaccess
Labels: component:identity, deploy, target:8.8, 8.8.0

#6583 feat(console): add experimental flags section
  docs/self-managed/components/console/configuration/configuration.md
Labels: 8.8.0-alpha8

#6567 docs(migration): add migration guide updating from gRPC to REST
  docs/apis-tools/migration-manuals/index.md
  docs/apis-tools/migration-manuals/migrate-from-grpc-to-orchestration-cluster-api.md
  docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
  sidebars.js
Labels: deploy, 8.8.0

#6543 docs(self-managed): helm upgrade for orchestration cluster consolidation
  docs/self-managed/concepts/elasticsearch-without-cluster-privileges.md
  docs/self-managed/installation-methods/helm/install.md
  docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
  docs/self-managed/operational-guides/backup-restore/restore.md
Labels: component:self-managed, deploy

#6595 docs: add bitname repo change to the announcements
  .github/workflows/build-docs.yaml
  docs/reference/announcements-release-notes/850/850-announcements.md
  docs/reference/announcements-release-notes/860/860-announcements.md
  docs/reference/announcements-release-notes/870/870-announcements.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
  docs/self-managed/installation-methods/helm/configure/air-gapped-installation.md
  docs/self-managed/installation-methods/helm/upgrade/helm-820-830.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md
  versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
  versioned_docs/version-8.5/self-managed/setup/guides/air-gapped-installation.md
  versioned_docs/version-8.5/self-managed/setup/upgrade.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.6/self-managed/setup/guides/air-gapped-installation.md
  versioned_docs/version-8.6/self-managed/setup/upgrade.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.7/self-managed/setup/guides/air-gapped-installation.md
  versioned_docs/version-8.7/self-managed/setup/upgrade.md
Labels: available & undocumented

#6552 docs(data-migrator): move docs over to `docs.camunda.io`
  docs/guides/migrating-from-camunda-7/data-migrator/config-examples.md
  docs/guides/migrating-from-camunda-7/data-migrator/config-properties.md
  docs/guides/migrating-from-camunda-7/data-migrator/database.md
  docs/guides/migrating-from-camunda-7/data-migrator/history.md
  docs/guides/migrating-from-camunda-7/data-migrator/index.md
  docs/guides/migrating-from-camunda-7/data-migrator/install.md
  docs/guides/migrating-from-camunda-7/data-migrator/limitations.md
  docs/guides/migrating-from-camunda-7/data-migrator/runtime.md
  docs/guides/migrating-from-camunda-7/data-migrator/troubleshooting.md
  docs/guides/migrating-from-camunda-7/data-migrator/variables.md
  docs/guides/migrating-from-camunda-7/data-migrator/version-compatibility.md
  docs/guides/migrating-from-camunda-7/migration-tooling.md
  sidebars.js
Labels: 8.8.0

#6607 Fix nesting of upgrade docs
  sidebars.js
Labels: support, deploy

#6609 Fix react component css hierarchy
  docs/apis-tools/react-components/_apitools-card-data.js
  docs/apis-tools/react-components/_apitools-card.css
  docs/apis-tools/react-components/_apitools-card.js
  docs/apis-tools/working-with-apis-tools.md
Labels: kind/bug, component:docs

#6606 docs: dual-region eks add note about gp3
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/dual-region.md
Labels: component:self-managed, deploy

#6518 fix: helm chart secrets refactor documentation update
  docs/self-managed/installation-methods/helm/configure/secret-management.md
Labels: deploy

#6435 fix: adjust indentation and typo in testing process definitions
  docs/components/best-practices/development/testing-process-definitions.md
Labels: low prio

#6611 Using Camunda redirects for content moves
  docs/apis-tools/administration-api/authentication.md
  docs/apis-tools/migration-manuals/index.md
  docs/apis-tools/working-with-apis-tools.md
  docs/components/best-practices/architecture/sizing-your-environment.md
  docs/components/components-overview.md
  docs/components/console/manage-clusters/cluster-backups.md
  docs/components/console/manage-clusters/create-cluster-include.md
  docs/components/console/manage-clusters/manage-cluster.md
  docs/components/console/manage-organization/manage-users.md
  docs/components/saas/auto-updates.md
  docs/components/saas/backups.md
  docs/components/saas/data-retention.md
  docs/components/saas/encryption-at-rest.md
  docs/components/saas/help-center.md
  docs/components/saas/img/automation-project-guide.png
  docs/components/saas/img/diagram-regions-map.png
  docs/components/saas/img/open-help-center.png
  docs/components/saas/ip-addresses.md
  docs/components/saas/regions.md
  docs/components/saas/saas.md
  docs/components/saas/status.md
  docs/reference/announcements-release-notes/860/860-release-notes.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
  docs/reference/img/orchestration-cluster.png
  docs/self-managed/about-self-managed.md
  docs/self-managed/components/components-upgrade/elasticsearch/7-to-8.md
  docs/self-managed/update/administrators/overview.md
  docs/self-managed/update/administrators/prepare-for-update.md
  docusaurus.config.js
  sidebars.js
  static/.htaccess
Labels: component:docs, deploy, theme:restructure

#6610 chore(element-templates): document how to edit element template on a local env
  docs/components/modeler/desktop-modeler/element-templates/configuring-templates.md
  docs/components/modeler/desktop-modeler/element-templates/using-templates.md
  docs/components/modeler/element-templates/defining-templates.md
  docs/components/modeler/web-modeler/element-templates/using-templates.md
Labels: component:web-modeler-SaaS, component:desktop-modeler, 8.8.0-alpha8

#6597 feat: document new exporter delete api for zeebe
  docs/self-managed/components/components-upgrade/870-to-880.md
  docs/self-managed/components/orchestration-cluster/zeebe/operations/management-api.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/management-api.md
Labels: deploy, 8.8.0-alpha8, 8.7.12

#6631 Self-Managed landing page updates
  docs/apis-tools/img/hero-apis.png
  docs/components/assets/hero-using-camunda.png
  docs/components/whats-new-in-88.md
  docs/guides/img/hero-get-started.png
  docs/self-managed/about-self-managed.md
  docs/self-managed/assets/hero-self-managed.png
  src/components/CamundaSelfManaged/Components.jsx
  src/components/CamundaSelfManaged/Infrastructure.jsx
  src/components/CamundaSelfManaged/Installation.jsx
  src/components/CamundaSelfManaged/Introduction.jsx
  src/components/CamundaSelfManaged/QuickStart.jsx
  src/components/CamundaSelfManaged/ReferenceArchitecture.jsx
  src/components/CamundaSelfManaged/icons/icon-connectors.png
  src/components/CamundaSelfManaged/icons/icon-connectors.svg
  src/components/CamundaSelfManaged/icons/icon-console.png
  src/components/CamundaSelfManaged/icons/icon-console.svg
  src/components/CamundaSelfManaged/icons/icon-identity.svg
  src/components/CamundaSelfManaged/icons/icon-modeler.png
  src/components/CamundaSelfManaged/icons/icon-modeler.svg
  src/components/CamundaSelfManaged/icons/icon-optimize.png
  src/components/CamundaSelfManaged/icons/icon-optimize.svg
  src/components/CamundaSelfManaged/icons/icon-orchcluster.png
  src/components/CamundaSelfManaged/icons/icon-orchestration-cluster.svg
  src/components/CamundaSelfManaged/styles.css
  src/theme/DocCard/index.tsx
  src/theme/DocCard/styles.module.css
Labels: component:docs, component:self-managed, deploy

#4905 feat: add documentation for filesystem backup store #2287
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/broker.md
  docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
Labels: deploy, target:8.8

#6633 docs(agentic-ai): add docs for openai-compatible provider
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
Labels: agentic orchestration, 8.8.0-alpha8

#6528 feat(idp-reference): added documentation for composability
  docs/components/modeler/web-modeler/idp/idp-configuration.md
Labels: 8.8.0-alpha8

#6569 Addressed feedback from several users
  docs/self-managed/update/administrators/assets/icon-backup.png
  docs/self-managed/update/administrators/assets/icon-prereqs.png
  docs/self-managed/update/administrators/assets/icon-restore.png
  docs/self-managed/update/administrators/overview.md
  docs/self-managed/update/administrators/prepare-for-update.md
  docs/self-managed/update/administrators/react-components/_card-data.js
  docs/self-managed/update/administrators/react-components/_card.css
  docs/self-managed/update/administrators/run-update.md
Labels: component:self-managed, deploy, 8.8.0

#6599 880-alpha8 release notes
  docs/reference/announcements-release-notes/880/880-release-notes.md
Labels: component:docs, deploy, 8.8.0-alpha8

#6507 feat(webmodeler): add section to use different database vendors
  docs/reference/supported-environments.md
  docs/self-managed/components/modeler/web-modeler/configuration/configuration.md
  docs/self-managed/components/modeler/web-modeler/configuration/database.md
Labels: component:web-modeler-sm, deploy, 8.8.0-alpha8

#6461 feat: set REST as default for the camunda client
  docs/apis-tools/camunda-spring-boot-starter/getting-started.md
  docs/apis-tools/java-client/getting-started.md
  docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
  docs/reference/announcements-release-notes/880/880-announcements.md
Labels: 8.8.0

#6643 docs: zeebe backups can be listed by prefix
  docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
Labels: support, available & undocumented

#6667 chore(element-templates): improve new content
  docs/components/best-practices/cicd-guidelines/element-templates-at-scale.md
  docs/components/best-practices/cicd-guidelines/img/pipeline-goal.png
  docs/components/concepts/assets/element-templates/properties-with-template.png
  docs/components/modeler/element-templates/element-template-with-dependencies.md
  docs/components/modeler/element-templates/img/element-template-dependencies.png
Labels: component:web-modeler-SaaS, component:web-modeler-sm, 8.8.0-alpha8

#6661 Update support page
  docs/apis-tools/react-components/_banner-ask-ai.md
  docs/components/react-components/_banner-ask-ai.md
  docs/guides/react-components/_banner-ask-ai.md
  docs/reference/contact.md
  docs/reference/img/icon-feature-request.png
  docs/reference/react-components/_banner-ask-ai.md
  versioned_docs/version-8.5/reference/contact.md
  versioned_docs/version-8.6/reference/contact.md
  versioned_docs/version-8.7/reference/contact.md
Labels: component:docs, deploy, available & undocumented

#6691 docs(helm): restructure registry and images section with subpages
  docs/self-managed/installation-methods/helm/configure/registry-and-images/air-gapped-installation.md
  docs/self-managed/installation-methods/helm/configure/registry-and-images/index.md
  docs/self-managed/installation-methods/helm/configure/registry-and-images/install-bitnami-enterprise-images.md
  docs/self-managed/installation-methods/helm/install.md
  sidebars.js
Labels: deploy, 8.8.0

#6664 docs: on increasing replica count during upgrade to 8.8
  docs/self-managed/components/components-upgrade/870-to-880.md
Labels: deploy, 8.8.0

#6624 Ad-hoc sub-process job worker docs
  docs/components/modeler/bpmn/ad-hoc-subprocesses/ad-hoc-subprocesses.md
  docs/components/modeler/bpmn/ad-hoc-subprocesses/assets/ad-hoc-subprocess-job-sequence-diagram.png
Labels: deploy, 8.8.0

#6687 chore(element-templates): fix warning around multiple templates in a single file
  docs/components/modeler/using-web-and-desktop-modeler-together.md
Labels: component:web-modeler-SaaS, component:desktop-modeler, component:web-modeler-sm, low prio

#6747 refactor: highlight what chart param tables are about
  docs/self-managed/installation-methods/helm/chart-parameters.md
Labels: low prio, 8.8.0

#6355 Add documentation for restored gRPC thread properties
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/gateway.md
Labels: 8.8.0

#6755 doc(announcements): Increasing replica count during upgrade to 8.8
  docs/reference/announcements-release-notes/880/880-announcements.md
Labels: 8.8.0

#6719 6718 authentication concepts overview for self-managed and management identity clean up
  docs/components/concepts/access-control/authorizations.md
  docs/components/concepts/access-control/connect-to-identity-provider.md
  docs/components/concepts/access-control/mapping-rules.md
  docs/components/orchestration-cluster.md
  docs/components/tasklist/userguide/using-tasklist.md
  docs/components/zeebe/zeebe-overview.md
  docs/guides/react-components/_install-plain-java.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
  docs/reference/announcements-release-notes/880/whats-new-in-88.md
  docs/self-managed/components/management-identity/access-management/access-management-overview.md
  docs/self-managed/components/management-identity/access-management/manage-permissions.md
  docs/self-managed/components/management-identity/application-user-group-role-management/applications.md
  docs/self-managed/components/management-identity/application-user-group-role-management/identity-application-user-group-role-management-overview.md
  docs/self-managed/components/management-identity/application-user-group-role-management/manage-groups.md
  docs/self-managed/components/management-identity/application-user-group-role-management/manage-roles.md
  docs/self-managed/components/management-identity/authentication.md
  docs/self-managed/components/management-identity/configuration/configure-external-identity-provider.md
  docs/self-managed/components/management-identity/configuration/connect-to-an-existing-keycloak.md
  docs/self-managed/components/management-identity/configuration/connect-to-an-oidc-provider.md
  docs/self-managed/components/management-identity/configuration/identity-configuration-overview.md
  docs/self-managed/components/management-identity/identity-first-steps.md
  docs/self-managed/components/management-identity/manage-tenants.md
  docs/self-managed/components/management-identity/mapping-rules.md
  docs/self-managed/components/management-identity/miscellaneous/application-monitoring.md
  docs/self-managed/components/management-identity/miscellaneous/troubleshoot-identity.md
  docs/self-managed/components/management-identity/overview.md
  docs/self-managed/components/management-identity/what-is-identity.md
  docs/self-managed/components/optimize/overview.md
  docs/self-managed/components/orchestration-cluster/identity/bring-your-own-groups.md
  docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider.md
  docs/self-managed/components/orchestration-cluster/identity/overview.md
  docs/self-managed/components/orchestration-cluster/tasklist/tasklist-authentication.md
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/broker.md
  docs/self-managed/components/orchestration-cluster/zeebe/configuration/gateway.md
  docs/self-managed/components/orchestration-cluster/zeebe/overview.md
  docs/self-managed/components/orchestration-cluster/zeebe/security/client-authorization.md
  docs/self-managed/concepts/authentication/authentication-to-management-components.md
  docs/self-managed/concepts/authentication/authentication-to-orchestration-cluster.md
  docs/self-managed/concepts/authentication/m2m-tokens.md
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
  docs/self-managed/installation-methods/helm/cloud-providers/azure/microsoft-aks/aks-helm.md
  docs/self-managed/installation-methods/helm/configure/configure-multi-tenancy.md
  docs/self-managed/installation-methods/helm/configure/using-existing-keycloak.md
  docs/self-managed/reference-architecture/kubernetes.md
  docs/self-managed/reference-architecture/reference-architecture.md
  sidebars.js
  src/components/CamundaSelfManaged/Components.jsx
  static/.htaccess
Labels: component:identity, deploy, target:8.8, 8.8.0

#6758 fix: do not invoke scrollToHash if no diagrams are present in the page
  static/js/render-diagrams.js
Labels: javascript

#6772 fix: remove trouble shooting guide c8run
  docs/self-managed/quickstart/developer-quickstart/c8run.md
Labels: component:self-managed

#6686 docs(c8run): mention no-db support for C8Run
  docs/self-managed/concepts/no-secondary-storage.md
Labels: 8.8.0

#6748 docs(data-migrator): document '.tenantIds' property in config-properties
  docs/guides/migrating-from-camunda-7/data-migrator/config-properties.md
  docs/guides/migrating-from-camunda-7/data-migrator/history.md
  docs/guides/migrating-from-camunda-7/data-migrator/limitations.md
  docs/guides/migrating-from-camunda-7/data-migrator/runtime.md
Labels: 8.8.0

#6783 chore: manual installation unified-config changes
  docs/self-managed/installation-methods/manual/install.md
Labels: component:self-managed, target:8.8

#6787 docs(sm): update Entra ID IdP configuration example to use default usernameClaim oid
  docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider.md
Labels: component:self-managed, 8.8.0

#6761 docs(helm): align Configure components page with template
  docs/self-managed/installation-methods/helm/configure/application-configs.md
Labels: component:self-managed, deploy, 8.6.0, self-managed:helm

#6784 chore(copilot): added documentation for routing in feel copilot
  docs/components/modeler/feel/assets/feel-playground-example-error-json.png
  docs/components/modeler/feel/assets/feel-playground-example-invalid-expression.png
  docs/components/modeler/feel/assets/feel-playground-example-warning-json.png
  docs/components/modeler/feel/assets/feel-playground-example.png
  docs/components/modeler/feel/assets/feel-playground-prompting-example.png
  docs/components/modeler/feel/assets/feel-playground-provider-specific-prompting-example.png
  docs/components/modeler/feel/feel-playground.md
Labels: deploy

#6828 docs(helm): align Helm chart air-gapped environment installation with template
  docs/self-managed/installation-methods/helm/configure/registry-and-images/air-gapped-installation.md
Labels: component:self-managed, 8.8.0, self-managed:helm

#6831 fix: correctly format oneOf primitive branch
  package-lock.json
  package.json
Labels: deploy

#6851 Identity: Management Identity 6718 retro review
  docs/self-managed/components/management-identity/access-management/access-management-overview.md
  docs/self-managed/components/management-identity/application-user-group-role-management/manage-roles.md
  docs/self-managed/components/management-identity/configuration/configure-external-identity-provider.md
  docs/self-managed/components/management-identity/configuration/connect-to-an-oidc-provider.md
  docs/self-managed/components/management-identity/configuration/identity-configuration-overview.md
  docs/self-managed/components/management-identity/manage-tenants.md
  docs/self-managed/components/management-identity/mapping-rules.md
  docs/self-managed/components/management-identity/miscellaneous/application-monitoring.md
  docs/self-managed/components/management-identity/miscellaneous/configuration-variables.md
  docs/self-managed/components/management-identity/miscellaneous/troubleshoot-identity.md
  docs/self-managed/components/management-identity/overview.md
  docs/self-managed/components/orchestration-cluster/identity/overview.md
  docs/self-managed/concepts/authentication/authentication-to-management-components.md
  docs/self-managed/concepts/authentication/authentication-to-orchestration-cluster.md
Labels: component:identity, 8.8.0

#6822 [CPT] Update docs and migration guide
  docs/apis-tools/migration-manuals/migrate-to-camunda-process-test.md
  docs/apis-tools/testing/assertions.md
  docs/apis-tools/testing/assets/process-coverage-report.png
  docs/apis-tools/testing/configuration.md
  docs/apis-tools/testing/connectors.md
  docs/apis-tools/testing/getting-started.md
  docs/apis-tools/testing/utilities.md
Labels: deploy

#6809 docs(data-migrator): document tenants in runtime
  docs/guides/migrating-from-camunda-7/data-migrator/config-properties.md
  docs/guides/migrating-from-camunda-7/data-migrator/runtime.md
Labels: 8.8.0

#6839 docs(sm-connectors-config): Document how to configure a truststore for the connectors Runtime
  docs/self-managed/components/connectors/connectors-configuration.md
  versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
Labels: low prio, available & undocumented

#6872 docs(data-migrator): runtime migrator updates skipReason
  docs/guides/migrating-from-camunda-7/data-migrator/limitations.md
Labels: 8.8.0

#6807 Describe task listener limitations for tasklist v1
  docs/components/concepts/user-task-listeners.md
  docs/components/tasklist/api-versions.md
Labels: deploy, 8.8.0

#6823 docs(inbound-connectors): Document Process Definitions polling limitations
  docs/components/connectors/connector-types.md
  versioned_docs/version-8.5/components/connectors/connector-types.md
  versioned_docs/version-8.6/components/connectors/connector-types.md
  versioned_docs/version-8.7/components/connectors/connector-types.md
Labels: low prio, available & undocumented

#6618 draft SAP and ServiceNow sidebar
  docs/components/camunda-integrations/overview.md
  docs/components/camunda-integrations/sap/camunda-sap-integration.md
  docs/components/camunda-integrations/sap/prerequisites.md
  docs/components/camunda-integrations/servicenow/servicenow-integration.md
  sidebars.js
Labels: deploy, target:8.8

#6847 chore(docs): include limitation around tasklist data retention
  versioned_docs/version-8.6/self-managed/tasklist-deployment/data-retention.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/data-retention.md
Labels: kind/bug

#6812 doc(self-managed): various adjustments regarding ref arch hld
  docs/self-managed/installation-methods/helm/assets/camunda-platform-8-self-managed-architecture-diagram-combined-ingress.png
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
  docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/terraform-setup.md
  docs/self-managed/installation-methods/helm/cloud-providers/openshift/redhat-openshift.md
  docs/self-managed/installation-methods/helm/configure/ingress-setup.md
  docs/self-managed/installation-methods/helm/index.md
  docs/self-managed/reference-architecture/img/k8s-cluster-view-orchestration.jpg
  docs/self-managed/reference-architecture/img/management-cluster.jpg
  docs/self-managed/reference-architecture/kubernetes.md
  docs/self-managed/reference-architecture/reference-architecture.md
  sidebars.js
Labels: component:self-managed, deploy

#6825 doc(self-managed): adjust bitnami cve and presentation
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
  docs/self-managed/installation-methods/helm/chart-parameters.md
  docs/self-managed/installation-methods/helm/configure/ingress-setup.md
  docs/self-managed/installation-methods/helm/configure/registry-and-images/air-gapped-installation.md
  docs/self-managed/installation-methods/helm/configure/registry-and-images/install-bitnami-enterprise-images.md
  docs/self-managed/installation-methods/helm/install.md
  docs/self-managed/operational-guides/troubleshooting.md
Labels: component:self-managed, deploy, self-managed:helm

#6887 docs(api): mention Swagger CSRF
  docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-swagger.md
Labels: 8.8.0

#6791 Agentic AI: Adapt documentation for new ad-hoc sub-process implementation
  docs/components/agentic-orchestration/ai-agents.md
  docs/components/connectors/img/agenticai-tool-resolution.png
  docs/components/connectors/img/agenticai-tools-loop-empty.png
  docs/components/connectors/img/agenticai-user-feedback-loop.png
  docs/components/connectors/img/ai-agent-ad-hoc-sub-process-multi-instance.png
  docs/components/connectors/img/ai-agent-loop-overview.png
  docs/components/connectors/img/ai-agent-process-user-feedback-loop.png
  docs/components/connectors/img/ai-agent-process.png
  docs/components/connectors/img/ai-agent-task-feedback-loop-advanced.png
  docs/components/connectors/img/ai-agent-task-feedback-loop.png
  docs/components/connectors/img/ai-agent-task-simple.png
  docs/components/connectors/img/ai-agent-task-user-feedback-loop.png
  docs/components/connectors/img/ai-agent-tool-resolution-fromAi.png
  docs/components/connectors/img/ai-agent-tool-resolution.png
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-ahsp-tools-schema-resolver.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-customization.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-example.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-process-example.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-process.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-task-example.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-task.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent-tool-definitions.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_error-handling.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_event-handling.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_execution-listeners.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_limits.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_memory-process.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_memory-storage-backends.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_memory-task.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_model-provider.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_model.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_output-mapping-process.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_output-mapping-task.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_response-fields-process.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_response.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_retries.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_system-prompt.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_tools.md
  docs/components/connectors/out-of-the-box-connectors/agentic-ai/aiagent/configuration/_user-prompt.md
  docs/components/early-access/alpha/mcp-client/img/mcp-client-hitl.png
  docs/components/early-access/alpha/mcp-client/mcp-client-connector.md
  docs/components/early-access/alpha/mcp-client/mcp-client.md
  docs/components/early-access/alpha/mcp-client/mcp-remote-client-connector.md
  docs/reference/announcements-release-notes/880/880-release-notes.md
  sidebars.js
  static/.htaccess
  static/bpmn/components/agentic-orchestration/ai-agents/agenticai-tool-resolution.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-process-user-feedback-loop.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-process.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-task-feedback-loop-advanced.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-task-feedback-loop.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-task-simple.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/ai-agent-task-user-feedback-loop.bpmn
  static/bpmn/components/agentic-orchestration/ai-agents/mcp-client-hitl.bpmn
Labels: deploy, 8.8.0
