Repository camunda/camunda-docs, pull requests merged in 2025-04, with the labels that each got.

#5406 docs(proxy): add proxy documentation
  docs/components/connectors/protocol/rest.md
  docs/images/connectors/connectors-rest-upload.png
  versioned_docs/version-8.6/components/connectors/protocol/rest.md
  versioned_docs/version-8.7/components/connectors/protocol/rest.md
Labels: deploy, 8.7.0

#5414 Clarify replication factor change for dual region failover
  docs/self-managed/operational-guides/multi-region/dual-region-ops.md
  versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
  versioned_docs/version-8.7/self-managed/operational-guides/multi-region/dual-region-ops.md
Labels: available & undocumented

#5425 Add IDP application settings
  docs/components/modeler/web-modeler/idp/idp-applications.md
  docs/components/modeler/web-modeler/idp/img/idp-application.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-applications.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/idp-application.png
Labels: component:web-modeler-SaaS, component:web-modeler-sm, target:8.7, deploy

#5424 Clarify the cluster installation internals for partition distribution
  docs/self-managed/concepts/multi-region/dual-region.md
  versioned_docs/version-8.6/self-managed/concepts/multi-region/dual-region.md
  versioned_docs/version-8.7/self-managed/concepts/multi-region/dual-region.md
Labels: available & undocumented

#5396 moved from graphql to rest api in description
  docs/components/best-practices/architecture/understanding-human-tasks-management.md
  versioned_docs/version-8.6/components/best-practices/architecture/understanding-human-tasks-management.md
  versioned_docs/version-8.7/components/best-practices/architecture/understanding-human-tasks-management.md
Labels: low prio

#4791 feat: document new backup/restore procedure and webapps specific config
  docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
  docs/self-managed/operational-guides/backup-restore/optimize-backup.md
  docs/self-managed/operational-guides/backup-restore/webapps-backup.md
  sidebars.js
Labels: component:zeebe, component:operate, component:tasklist, component:optimize, target:8.8

#5319 create a guide for es prefix settings
  docs/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  sidebars.js
  versioned_docs/version-8.5/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.6/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.7/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_sidebars/version-8.5-sidebars.json
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: low prio

#5427 IDP landing page
  docs/components/modeler/web-modeler/idp/idp-configuration.md
  docs/components/modeler/web-modeler/idp/img/icon-config.png
  docs/components/modeler/web-modeler/idp/img/icon-example.png
  docs/components/modeler/web-modeler/idp/img/icon-idp-application.png
  docs/components/modeler/web-modeler/idp/img/icon-idp-extraction.png
  docs/components/modeler/web-modeler/idp/img/icon-idp-integrate.png
  docs/components/modeler/web-modeler/idp/img/icon-prereqs.png
  docs/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
  docs/components/modeler/web-modeler/idp/react-components/_idp-card.js
  docs/components/modeler/web-modeler/idp/react-components/_idp-table.css
  docs/components/modeler/web-modeler/intelligent-document-processing.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-config.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-example.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-idp-application.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-idp-extraction.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-idp-integrate.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/icon-prereqs.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-card.js
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-table.css
  versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md
Labels: component:docs, target:8.7, deploy

#5373 fix: remove reference of document url
  docs/components/concepts/assets/document-preview-settings.png
  docs/components/concepts/assets/document-preview.png
  docs/components/modeler/forms/form-element-library/forms-element-library-document-preview.md
  docs/components/tasklist/userguide/using-tasklist.md
  versioned_docs/version-8.7/components/concepts/assets/document-preview-settings.png
  versioned_docs/version-8.7/components/concepts/assets/document-preview.png
  versioned_docs/version-8.7/components/modeler/forms/form-element-library/forms-element-library-document-preview.md
  versioned_docs/version-8.7/components/tasklist/userguide/using-tasklist.md
Labels: deploy, 8.8.0-alpha3, 8.7.0

#5398 feat(process readmes): added docs for process app readmes
  docs/components/modeler/web-modeler/advanced-modeling/img/download-readme.png
  docs/components/modeler/web-modeler/advanced-modeling/img/process-application-with-readme.png
  docs/components/modeler/web-modeler/advanced-modeling/img/process-landscape-with-readme.png
  docs/components/modeler/web-modeler/advanced-modeling/img/project-with-readme.png
  docs/components/modeler/web-modeler/advanced-modeling/img/readme-preview.png
  docs/components/modeler/web-modeler/advanced-modeling/img/view-readme-versions.png
  docs/components/modeler/web-modeler/advanced-modeling/process-documentation-with-readme-files.md
  sidebars.js
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/download-readme.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/process-application-with-readme.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/process-landscape-with-readme.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/project-with-readme.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/readme-preview.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/img/view-readme-versions.png
  versioned_docs/version-8.7/components/modeler/web-modeler/advanced-modeling/process-documentation-with-readme-files.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:web-modeler-SaaS, component:web-modeler-sm, target:8.7

#5423 Move and align IDP and RPA
  docs/components/rpa/overview.md
  sidebars.js
  versioned_docs/version-8.7/components/rpa/overview.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: component:docs, target:8.7, deploy

#5439 IDP Self-Managed configuration
  docs/components/modeler/web-modeler/idp/idp-applications.md
  docs/components/modeler/web-modeler/idp/idp-configuration.md
  docs/components/modeler/web-modeler/idp/idp-integrate.md
  docs/components/modeler/web-modeler/idp/idp-reference.md
  docs/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
  docs/components/modeler/web-modeler/intelligent-document-processing.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-applications.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-integrate.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
  versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, target:8.7, deploy

#5441 chore: version bumps of external dependencies
  docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md
  versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md
  versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
Labels: component:self-managed, component:infex, target:8.7

#5432 small spring guide update
  docs/guides/getting-started-java-spring.md
  versioned_docs/version-8.7/guides/getting-started-java-spring.md
Labels: component:docs

#5426 docs(web-modeler): update actions possible on process app versions
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-action-menu-item-highlight.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-action-show-versions.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-actions.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-create-via-breadcrumb-highlight.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-create-via-versions-menu.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-show-via-breadcrumb-highlight.png
  docs/components/modeler/web-modeler/process-application-versioning.md
  docs/components/modeler/web-modeler/versions.md
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-action-menu-item-highlight.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-action-show-versions.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-actions.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-create-via-breadcrumb-highlight.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-create-via-versions-menu.png
  versioned_docs/version-8.7/components/modeler/web-modeler/img/versions/web-modeler-version-show-via-breadcrumb-highlight.png
  versioned_docs/version-8.7/components/modeler/web-modeler/process-application-versioning.md
  versioned_docs/version-8.7/components/modeler/web-modeler/versions.md
Labels: deploy, 8.7.0

#5435 docs: update Optimize screenshots for 8.7
  optimize/components/userguide/additional-features/img/alert-modal-description.png
  optimize/components/userguide/additional-features/img/alerts-overview.png
  optimize/components/userguide/img/addUser.png
  optimize/components/userguide/img/collection.png
  optimize/components/userguide/img/copy.png
  optimize/components/userguide/img/dashboad-descriptionModal.png
  optimize/components/userguide/img/dashboard-addAReportModal-externalReport.png
  optimize/components/userguide/img/dashboard-addAReportModal-textReport.png
  optimize/components/userguide/img/dashboard-addAReportModal.png
  optimize/components/userguide/img/dashboard-sharingPopover.png
  optimize/components/userguide/img/dashboard-showMoreDescription.png
  optimize/components/userguide/img/dashboardTemplate.png
  optimize/components/userguide/img/home.png
  optimize/components/userguide/img/report-descriptionModal.png
  optimize/components/userguide/img/report-reportEditActions.png
  optimize/components/userguide/img/reportTemplate.png
  optimize/components/userguide/img/users.png
  optimize/components/userguide/process-analysis/img/duration-filter.png
  optimize/components/userguide/process-analysis/report-analysis/img/NumberConfiguration.png
  optimize/components/userguide/process-analysis/report-analysis/img/durationAggregation.png
  optimize/components/userguide/process-analysis/report-analysis/img/heatmap.png
  optimize/components/userguide/process-analysis/report-analysis/img/progressbar.png
  optimize/components/userguide/process-analysis/report-analysis/img/progressbarExceeded.png
  optimize/components/userguide/process-analysis/report-analysis/img/report-sharingPopover.png
  optimize/components/userguide/process-analysis/report-analysis/img/report-showMoreDescription.png
Labels: deploy, 8.7.0

#5407 docs(web-modeler): document changes in authentication methods for configured clusters
  docs/reference/announcements-release-notes/870/870-announcements.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.7/self-managed/setup/guides/connect-to-an-oidc-provider.md
Labels: component:web-modeler-sm, 8.7.0

#5444 docs: infraex related doc adjustments
  docs/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
Labels: component:self-managed, component:infex, target:8.7

#5289 docs: document default log configuration
  docs/self-managed/zeebe-deployment/configuration/logging.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/logging.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/logging.md
Labels: deploy

#5363 Console Manage connectors
  docs/components/console/manage-clusters/img/cluster-connector-instance-details.png
  docs/components/console/manage-clusters/img/cluster-connector-instance-error.png
  docs/components/console/manage-clusters/img/cluster-connector-management-page.png
  docs/components/console/manage-clusters/img/cluster-connector-process-details.png
  docs/components/console/manage-clusters/img/cluster-manage-connectors.png
  docs/components/console/manage-clusters/manage-connectors.md
  sidebars.js
  versioned_docs/version-8.7/components/console/manage-clusters/img/cluster-connector-instance-details.png
  versioned_docs/version-8.7/components/console/manage-clusters/img/cluster-connector-instance-error.png
  versioned_docs/version-8.7/components/console/manage-clusters/img/cluster-connector-management-page.png
  versioned_docs/version-8.7/components/console/manage-clusters/img/cluster-connector-process-details.png
  versioned_docs/version-8.7/components/console/manage-clusters/img/cluster-manage-connectors.png
  versioned_docs/version-8.7/components/console/manage-clusters/manage-connectors.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: kind/feature, component:console, component:connectors, target:8.7, deploy

#5361 Remove AWS region backup limitation
  docs/reference/regions.md
  versioned_docs/version-8.3/reference/regions.md
  versioned_docs/version-8.4/reference/regions.md
  versioned_docs/version-8.5/reference/regions.md
  versioned_docs/version-8.6/reference/regions.md
  versioned_docs/version-8.7/reference/regions.md
Labels: component:console, target:8.7

#5456 Camunda 8 Run for IDP
  docs/components/modeler/web-modeler/idp/idp-configuration.md
  docs/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
Labels: kind/feature, component:web-modeler-SaaS, component:web-modeler-sm, target:8.7, deploy

#5457 Add Windows start to Camunda 8 Run
  docs/self-managed/setup/deploy/local/c8run.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md
Labels: component:self-managed, deploy

#4829 confine backup and restore breaking changes to the version they were introduced
  docs/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.3/reference/announcements.md
  versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
  versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.4/reference/announcements.md
  versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
  versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.5/reference/announcements.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
  versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/optimize-backup.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup-and-restore.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
  versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/optimize-backup.md
Labels: kind/feature, component:self-managed, deploy, low prio

#5428 Add permissions table for IDP
  docs/components/modeler/web-modeler/idp/idp-reference.md
  src/css/custom.css
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, target:8.7

#5220 fix: make link to c8run release dynamic
  docs/self-managed/setup/deploy/local/c8run.md
  src/components/CamundaDistributions/C8Run.jsx
  src/components/CamundaDistributions/index.jsx
  versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md
Labels: component:self-managed, deploy

#5468 Adding docker compose and doc handling limitations
  docs/self-managed/concepts/document-handling/configuration.md
  versioned_docs/version-8.7/self-managed/concepts/document-handling/configuration.md
Labels: deploy

#5431 fix: add another command and some elaboration to ops procedure so it is more general
  docs/self-managed/operational-guides/multi-region/dual-region-ops.md
  versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
  versioned_docs/version-8.7/self-managed/operational-guides/multi-region/dual-region-ops.md
Labels: deploy, low prio

#5231 Document `updating` user task listener
  docs/components/concepts/user-task-listeners.md
Labels: 8.8.0-alpha3

#5455 Add instructions for file association wiring of desktop modeler
  docs/components/modeler/desktop-modeler/index.md
  docs/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.3/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.3/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.4/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.4/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.5/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.5/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.6/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.6/components/modeler/desktop-modeler/install-the-modeler.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/index.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/install-the-modeler.md
Labels: low prio

#5434 doc(self-managed): integrate dual-region openshift as reference arch …
  docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  docs/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  docs/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
  docs/self-managed/setup/deploy/openshift/dual-region.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/openshift/dual-region.md
Labels: component:self-managed, component:infex, deploy

#5461 Add Amazon Bedrock regional limitations
  docs/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
Labels: kind/enhancement, component:web-modeler-SaaS, component:web-modeler-sm

#5462 IDP table data extraction
  docs/components/modeler/web-modeler/idp/idp-reference.md
  docs/components/modeler/web-modeler/idp/img/idp-table-data.png
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/img/idp-table-data.png
Labels: component:web-modeler-SaaS, component:web-modeler-sm, target:8.7, deploy, available & undocumented

#5470 chore: update 8.7 c8 REST API docs
  api/camunda/version-8.7/camunda-openapi.yaml
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/create-document-link.api.mdx
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/create-document.api.mdx
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/create-documents.api.mdx
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/delete-document.api.mdx
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/get-document.api.mdx
Labels: dx, target:8.7, component:api

#5433 update shared project guide
  docs/guides/use-shared-project-for-organization-wide-collaboration.md
  versioned_docs/version-8.6/components/modeler/web-modeler/git-sync.md
  versioned_docs/version-8.7/guides/use-shared-project-for-organization-wide-collaboration.md
Labels: target:8.7, deploy, 8.7.0

#5416 feat: scaffold new process applications documentation
  docs/components/concepts/assets/process-applications/diagram-process-application-get-started.png
  docs/components/concepts/process-applications.md
  docs/components/modeler/desktop-modeler/img/process-applications/grouping.png
  docs/components/modeler/desktop-modeler/img/process-applications/link-resources.png
  docs/components/modeler/desktop-modeler/img/process-applications/overlay.png
  docs/components/modeler/desktop-modeler/process-applications.md
  docs/components/modeler/web-modeler/process-applications.md
  sidebars.js
  versioned_docs/version-8.7/components/concepts/assets/process-applications/diagram-process-application-get-started.png
  versioned_docs/version-8.7/components/concepts/process-applications.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/img/process-applications/grouping.png
  versioned_docs/version-8.7/components/modeler/desktop-modeler/img/process-applications/link-resources.png
  versioned_docs/version-8.7/components/modeler/desktop-modeler/img/process-applications/overlay.png
  versioned_docs/version-8.7/components/modeler/desktop-modeler/process-applications.md
  versioned_docs/version-8.7/components/modeler/web-modeler/process-applications.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: target:8.7, 8.7.0

#5466 Revert ingress changes
  docs/self-managed/operational-guides/troubleshooting/troubleshooting.md
  docs/self-managed/setup/guides/ingress-setup.md
  versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md
  versioned_docs/version-8.7/self-managed/setup/deploy/local/local-kubernetes-cluster.md
  versioned_docs/version-8.7/self-managed/setup/guides/ingress-setup.md
  versioned_docs/version-8.7/self-managed/setup/install.md
Labels: component:self-managed, target:8.7

#4605 Flag and update the keycloak port
  docs/guides/host-custom-connector.md
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
  docs/self-managed/setup/deploy/other/docker.md
  docs/self-managed/zeebe-deployment/configuration/broker.md
  docs/self-managed/zeebe-deployment/configuration/gateway.md
  docs/self-managed/zeebe-deployment/security/client-authorization.md
Labels: component:identity, component:self-managed

#5467 improve processes documentation
  docs/components/concepts/processes.md
  versioned_docs/version-8.6/components/concepts/processes.md
  versioned_docs/version-8.7/components/concepts/processes.md
Labels: target:8.7

#5454 docs(self-managed): Secret Management Guide
  docs/self-managed/setup/guides/secret-management.md
  sidebars.js
  versioned_docs/version-8.6/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.7/self-managed/setup/guides/secret-management.md
  versioned_sidebars/version-8.6-sidebars.json
  versioned_sidebars/version-8.7-sidebars.json
Labels: target:8.7, deploy, 8.8.0-alpha3, 8.7.0

#5480 docs: document known issues for 8.7 release
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: target:8.7

#5482 Update the C8Run components to use the dynamic link
  docs/guides/react-components/_install-c8run.md
  versioned_docs/version-8.6/guides/react-components/_install-c8run.md
  versioned_docs/version-8.7/guides/react-components/_install-c8run.md
Labels: deploy

#5465 8.7 release
  docusaurus.config.js
  src/versions.js
  static/.htaccess
  versioned_docs/version-8.6/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.6/components/best-practices/best-practices-overview.md
  versioned_docs/version-8.7/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md
  versioned_docs/version-8.7/apis-tools/tasklist-api-rest/assets/forms/userTaskMigrationDecisionHelperForm.js
  versioned_docs/version-8.7/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.7/components/best-practices/best-practices-overview.md
  versioned_docs/version-8.7/components/concepts/document-handling.md
  versioned_docs/version-8.7/components/modeler/forms/form-element-library/forms-element-library-document-preview.md
  versioned_docs/version-8.7/components/modeler/forms/form-element-library/forms-element-library-filepicker.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/guides/document-handling.md
  versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
  versioned_docs/version-8.7/self-managed/concepts/document-handling/overview.md
Labels: dx, deploy

#5483 ci: trigger an algolia crawl after production publish
  .github/workflows/publish-prod.yaml
Labels: kind/enhancement, dx

#5481 Infraex 8.7 docs adjustments v2/99
  docs/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
  versioned_docs/version-8.7/self-managed/setup/deploy/openshift/redhat-openshift.md
Labels: component:self-managed, component:infex, target:8.7

#5486 Fix links on document-handling guide
  docs/guides/document-handling.md
  versioned_docs/version-8.7/guides/document-handling.md
Labels: kind/bug, target:8.7

#5304 task listeners are supported with 8.8
  docs/guides/migrating-from-camunda-7/technical-details.md
Labels: c7migration, target:8.8

#5489 fix: remove unsupported updating trigger
  docs/components/concepts/user-task-listeners.md
Labels: bug, 8.8.0-alpha3

#5279 docs: add security notice 17 (Check Publication date before publishing)
  docs/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: component:zeebe

#5490 docs: last adjustments removing a feature branch
  docs/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  docs/self-managed/setup/deploy/openshift/dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
  versioned_docs/version-8.7/self-managed/setup/deploy/openshift/dual-region.md
Labels: component:self-managed, component:infex, target:8.7

#5495 Known bugs format
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: component:docs, target:8.7, deploy, available & undocumented

#5500 fix: adjust desktop modeler process application docs
  docs/components/modeler/desktop-modeler/process-applications.md
  versioned_docs/version-8.7/components/modeler/desktop-modeler/process-applications.md
Labels: low prio

#5491 Add IDP connector secrets link
  docs/components/modeler/web-modeler/idp/idp-configuration.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, available & undocumented

#5501 Fix IDP region typo
  docs/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
Labels: component:docs, low prio

#5300 feat: change sdk default for maxMessageSize
  docs/apis-tools/spring-zeebe-sdk/configuration.md
  versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
  versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md
  versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md
Labels: low prio

#5440 fix: Add debug logging config to the Connectors doc
  docs/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.4/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
  versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
Labels: available & undocumented

#5412 docs(web-modeler): link to project permissions
  docs/apis-tools/web-modeler-api/authentication.md
  docs/self-managed/identity/user-guide/roles/manage-permissions.md
  versioned_docs/version-8.6/apis-tools/web-modeler-api/authentication.md
  versioned_docs/version-8.6/self-managed/identity/user-guide/roles/manage-permissions.md
  versioned_docs/version-8.7/apis-tools/web-modeler-api/authentication.md
  versioned_docs/version-8.7/self-managed/identity/user-guide/roles/manage-permissions.md
Labels: component:web-modeler-sm, deploy, available & undocumented

#5471 chore: update add-to-project user IDs
  .github/workflows/add-to-project.yaml
Labels: dx

#5503 Add (back) 8.7 release announcements redirects
  static/.htaccess
Labels: kind/bug, target:8.7

#5487 minor tweaks to document handling
  docs/components/camunda-integrations/sap/btp-plugin.md
  docs/components/concepts/document-handling.md
  docs/components/modeler/forms/form-element-library/forms-element-library-filepicker.md
  docs/components/modeler/web-modeler/idp/idp-example.md
  docs/guides/document-handling.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/self-managed/concepts/document-handling/overview.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/btp-plugin.md
  versioned_docs/version-8.7/components/concepts/document-handling.md
  versioned_docs/version-8.7/components/modeler/forms/form-element-library/forms-element-library-filepicker.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-example.md
  versioned_docs/version-8.7/guides/document-handling.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/self-managed/concepts/document-handling/overview.md
Labels: component:docs

#5504 Add announcement to 8.5 to 8.6 update guide
  docs/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
Labels: component:docs, component:self-managed, available & undocumented

#5505 Change footer link to Release policy
  docusaurus.config.js
Labels: low prio

#5507 Remove Optimize 3.7 admonition
  docs/reference/announcements-release-notes/overview.md
  versioned_docs/version-8.6/reference/announcements-release-notes/overview.md
  versioned_docs/version-8.7/reference/announcements-release-notes/overview.md
Labels: component:docs, low prio

#5511 macOS not Mac OS
  versioned_docs/version-8.3/reference/supported-environments.md
  versioned_docs/version-8.4/reference/supported-environments.md
  versioned_docs/version-8.5/reference/supported-environments.md
  versioned_docs/version-8.6/reference/supported-environments.md
Labels: low prio

#5512 Add changelog links for 8.7
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/reference/announcements-release-notes/overview.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/overview.md
Labels: target:8.7, deploy

#5513 add redirects
  static/.htaccess
Labels: kind/bug, component:docs, target:8.7

#5516 Add update announcement
  docs/reference/announcements-release-notes/870/870-release-notes.md
  docs/self-managed/operational-guides/update-guide/830-to-840.md
  docs/self-managed/operational-guides/update-guide/840-to-850.md
  docs/self-managed/operational-guides/update-guide/850-to-860.md
  docs/self-managed/operational-guides/update-guide/860-to-870.md
  versioned_docs/version-8.4/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.5/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/830-to-840.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/840-to-850.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
Labels: bug

#5518 add self managed release note
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: component:docs, component:self-managed, target:8.7

#5502 docs: update es prefix guide based on customer feedback
  docs/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.5/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.6/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
  versioned_docs/version-8.7/self-managed/setup/guides/configure-elastcisearch-prefix-indices.md
Labels: component:self-managed, available & undocumented

#5527 Migration guide review: added missing todo
  docs/guides/migrating-from-camunda-7/code-conversion.md
Labels: low prio

#5523 Remove Operate and Tasklist bugs from 8.7, only applicable to 8.4
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: kind/bug, component:docs, target:8.7

#5531 Add first migration analyzer release to migration guide
  docs/guides/img/analyzer-result-excel.png
  docs/guides/img/analyzer-screenshot-1.png
  docs/guides/img/analyzer-screenshot-2.png
  docs/guides/migrating-from-camunda-7/migration-journey.md
  docs/guides/migrating-from-camunda-7/migration-tooling.md
  versioned_docs/version-8.7/guides/img/analyzer-result-excel.png
  versioned_docs/version-8.7/guides/img/analyzer-screenshot-1.png
  versioned_docs/version-8.7/guides/img/analyzer-screenshot-2.png
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md
  versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md
Labels: available & undocumented

#5535 chore(notices): adjust security notice 18
  docs/reference/notices.md
  versioned_docs/version-8.6/reference/notices.md
  versioned_docs/version-8.7/reference/notices.md
Labels: support

#5529 Add bug description in for SM Azure with Manged Identity in release 8.7.0.
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: kind/bug, target:8.7

#5526 add example to reference existingSecret in secret management guide
  docs/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.6/self-managed/setup/guides/secret-management.md
  versioned_docs/version-8.7/self-managed/setup/guides/secret-management.md
Labels: available & undocumented

#5498 Define dependency maintenance policy (incl. Spring)
  docs/reference/supported-environments.md
  versioned_docs/version-8.3/reference/supported-environments.md
  versioned_docs/version-8.4/reference/supported-environments.md
  versioned_docs/version-8.5/reference/supported-environments.md
  versioned_docs/version-8.6/reference/supported-environments.md
  versioned_docs/version-8.7/reference/supported-environments.md
Labels: target:8.8

#5546 update versioned links for 8.7
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/gateway.md
  versioned_docs/version-8.7/self-managed/operational-guides/configure-flow-control/configure-flow-control.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/configuration.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/gateway.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/backpressure.md
Labels: component:docs

#5547 docs housekeeping april
  docs/components/console/manage-clusters/cluster-backups.md
  docs/components/console/manage-clusters/manage-ip-allowlists.md
  docs/self-managed/zeebe-deployment/security/client-authorization.md
  versioned_docs/version-8.3/components/console/manage-clusters/manage-ip-allowlists.md
  versioned_docs/version-8.4/components/console/manage-clusters/cluster-backups.md
  versioned_docs/version-8.4/components/console/manage-clusters/manage-ip-allowlists.md
  versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
  versioned_docs/version-8.5/components/console/manage-clusters/cluster-backups.md
  versioned_docs/version-8.5/components/console/manage-clusters/manage-ip-allowlists.md
  versioned_docs/version-8.6/components/console/manage-clusters/cluster-backups.md
  versioned_docs/version-8.6/components/console/manage-clusters/manage-ip-allowlists.md
  versioned_docs/version-8.7/components/console/manage-clusters/cluster-backups.md
  versioned_docs/version-8.7/components/console/manage-clusters/manage-ip-allowlists.md
  versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/security/client-authorization.md
Labels: component:docs

#5393 docs: document default gRPC service config
  docs/apis-tools/zeebe-api/gateway-service.md
  versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md
  versioned_docs/version-8.5/apis-tools/zeebe-api/gateway-service.md
  versioned_docs/version-8.6/apis-tools/zeebe-api/gateway-service.md
  versioned_docs/version-8.7/apis-tools/zeebe-api/gateway-service.md
Labels: component:zeebe, available & undocumented

#5550 adjust 8.7 spring zeebe references
  docs/reference/announcements-release-notes/870/870-announcements.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
Labels: component:docs

#5544 add known issue link to rpa docs
  docs/components/rpa/getting-started.md
  docs/components/rpa/overview.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/components/rpa/getting-started.md
  versioned_docs/version-8.7/components/rpa/overview.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: component:docs

#5552 docs(data-purge): fix note formatting
  docs/self-managed/concepts/exporters.md
Labels: low prio

#5561 add next redirects for c7 only modeler content
  static/.htaccess
Labels: component:docs

#5551 add release blog to update guides
  docs/self-managed/operational-guides/update-guide/introduction.md
  versioned_docs/version-8.7/self-managed/operational-guides/update-guide/introduction.md
Labels: component:docs

#5525 Update version suggestion for 8.7/8.8
  .github/workflows/check-versions/version-config.json
Labels: dx, target:8.7

#5558 fix: tasklist actuator port is 9600
  docs/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
Labels: component:tasklist, low prio

#5570 feat: csap is now notarized by Apple
  docs/components/camunda-integrations/sap/csap-cli.md
  versioned_docs/version-8.7/components/camunda-integrations/sap/csap-cli.md
Labels: available & undocumented

#5567 chore: prepare for 8.3 archival
  .github/workflows/publish-prod.yaml
  howtos/versioning.md
Labels: kind/cleanup, dx, epic:archive-old-versions

#5530 CSS enhancements
  docs/components/console/manage-clusters/manage-connectors.md
  docs/components/modeler/web-modeler/idp/idp-example.md
  docs/components/modeler/web-modeler/idp/idp-integrate.md
  docs/components/modeler/web-modeler/idp/idp-key-concepts.md
  docs/components/modeler/web-modeler/idp/idp-reference.md
  docs/components/modeler/web-modeler/intelligent-document-processing.md
  docs/reference/regions.md
  src/css/custom.css
  versioned_docs/version-8.3/reference/regions.md
  versioned_docs/version-8.4/reference/regions.md
  versioned_docs/version-8.5/reference/regions.md
  versioned_docs/version-8.6/reference/regions.md
  versioned_docs/version-8.7/components/console/manage-clusters/manage-connectors.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-example.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-integrate.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-key-concepts.md
  versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
  versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md
  versioned_docs/version-8.7/reference/regions.md
Labels: component:docs, dx, deploy, low prio

#5575 fix broken link in process app pipeline
  docs/components/modeler/web-modeler/process-application-pipeline.md
  versioned_docs/version-8.7/components/modeler/web-modeler/process-application-pipeline.md
Labels: kind/bug, component:modeler, component:web-modeler-SaaS, component:web-modeler-sm

#5576 docs: change gateway management port to 9600 as example
  docs/self-managed/zeebe-deployment/configuration/broker.md
  docs/self-managed/zeebe-deployment/configuration/gateway.md
  versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/broker.md
  versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/gateway.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/gateway.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/broker.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/gateway.md
Labels: component:zeebe, component:self-managed

#5559 [AWS EKS][>8.7] Outsource additional scripts to reference repo
  docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
  versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
  versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
Labels: component:self-managed, component:infex, deploy

#5582 fix: Update 8.7 docs on batch file upload
  api/camunda/version-8.7/camunda-openapi.yaml
  versioned_docs/version-8.7/apis-tools/camunda-api-rest/specifications/create-documents.api.mdx
Labels: available & undocumented

#5560 document spring sdk modes
  docs/apis-tools/spring-zeebe-sdk/configuration.md
  versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md
Labels: low prio

#5578 fix: zeebe cluster-scale documentation still based on zbctl
  docs/self-managed/zeebe-deployment/operations/cluster-scaling.md
  versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/cluster-scaling.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/cluster-scaling.md
Labels: component:zeebe, component:self-managed, deploy

#5562 fix: document Swagger UI limitation for Operate API v.1
  docs/apis-tools/operate-api/overview.md
  versioned_docs/version-8.3/apis-tools/operate-api/overview.md
  versioned_docs/version-8.4/apis-tools/operate-api/overview.md
  versioned_docs/version-8.5/apis-tools/operate-api/overview.md
  versioned_docs/version-8.6/apis-tools/operate-api/overview.md
  versioned_docs/version-8.7/apis-tools/operate-api/overview.md
Labels: available & undocumented

#5580 add note for 8.7 helm update
  versioned_docs/version-8.7/self-managed/setup/upgrade.md
Labels: component:self-managed

#5583 Add glossary for element and flow node
  docs/reference/glossary.md
  versioned_docs/version-8.4/reference/glossary.md
  versioned_docs/version-8.5/reference/glossary.md
  versioned_docs/version-8.6/reference/glossary.md
  versioned_docs/version-8.7/reference/glossary.md
Labels: low prio

#5590 Micrometer metrics
  docs/self-managed/modeler/web-modeler/configuration/configuration.md
  docs/self-managed/modeler/web-modeler/configuration/logging.md
  docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
  docs/self-managed/operational-guides/monitoring/log-levels.md
  docs/self-managed/operational-guides/monitoring/metrics.md
  docs/self-managed/setup/deploy/amazon/aws-ec2.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/logging.md
  versioned_docs/version-8.6/self-managed/operational-guides/monitoring/log-levels.md
  versioned_docs/version-8.6/self-managed/operational-guides/monitoring/metrics.md
  versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md
  versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/logging.md
  versioned_docs/version-8.7/self-managed/operational-guides/monitoring/log-levels.md
  versioned_docs/version-8.7/self-managed/operational-guides/monitoring/metrics.md
Labels: kind/enhancement, component:zeebe, component:self-managed, deploy

#5592 Replay scenarios saas only
  docs/components/modeler/web-modeler/play-your-process.md
  docs/reference/announcements-release-notes/870/870-release-notes.md
  versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
  versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
Labels: support, component:web-modeler-SaaS, deploy

#5581 docs(exporter): remove Camunda exporter from 8.7 docs
  static/.htaccess
  versioned_docs/version-8.7/self-managed/setup/guides/configure-db-custom-headers.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/broker.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/camunda-exporter.md
  versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/exporters.md
  versioned_sidebars/version-8.7-sidebars.json
Labels: available & undocumented

#5532 docs(exporter): migration to single Elastic instance
  docs/reference/announcements-release-notes/880/880-announcements.md
  docs/self-managed/operational-guides/update-guide/870-to-880.md
Labels: target:8.8

#5587 archive(8.3) isolation: pt 2, reviewable steps
  .github/workflows/build-docs.yaml
  .github/workflows/publish-prod.yaml
  .github/workflows/publish-stage.yaml
  Dockerfile
  docusaurus.config.js
  src/pages/index.js
  src/theme/AnnouncementBar/index.js
  src/theme/DocVersionBanner/index.js
  src/versions.js
  static/.htaccess
  static/robots.txt
  versioned_docs/version-8.3/apis-tools/operate-api/overview.md
  versioned_docs/version-8.3/apis-tools/operate-api/tutorial.md
  versioned_docs/version-8.3/apis-tools/working-with-apis-tools.md
  versioned_docs/version-8.3/components/concepts/backups.md
  versioned_docs/version-8.3/components/concepts/messages.md
  versioned_docs/version-8.3/components/concepts/variables.md
  versioned_docs/version-8.3/components/concepts/workflow-patterns.md
  versioned_docs/version-8.3/components/connectors/introduction.md
  versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/amazon-eventbridge.md
  versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/google-maps-platform.md
  versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/slack.md
  versioned_docs/version-8.3/components/connectors/protocol/polling.md
  versioned_docs/version-8.3/components/connectors/use-connectors/index.md
  versioned_docs/version-8.3/components/console/manage-organization/enable-alpha-features.md
  versioned_docs/version-8.3/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md
  versioned_docs/version-8.3/components/modeler/bpmn/call-activities/call-activities.md
  versioned_docs/version-8.3/components/modeler/bpmn/message-events/message-events.md
  versioned_docs/version-8.3/components/modeler/bpmn/receive-tasks/receive-tasks.md
  versioned_docs/version-8.3/components/modeler/bpmn/service-tasks/service-tasks.md
  versioned_docs/version-8.3/components/modeler/bpmn/timer-events/timer-events.md
  versioned_docs/version-8.3/components/modeler/bpmn/user-tasks/user-tasks.md
  versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-error-handling.md
  versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-functions.md
  versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-string-expressions.md
  versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-variables.md
  versioned_docs/version-8.3/components/modeler/feel/what-is-feel.md
  versioned_docs/version-8.3/components/modeler/forms/form-element-library/forms-element-library-image.md
  versioned_docs/version-8.3/components/modeler/web-modeler/advanced-modeling/publish-public-processes.md
  versioned_docs/version-8.3/components/modeler/web-modeler/camunda-marketplace.md
  versioned_docs/version-8.3/components/tasklist/userguide/starting-processes.md
  versioned_docs/version-8.3/guides/configuring-out-of-the-box-connector.md
  versioned_docs/version-8.3/guides/getting-started-orchestrate-apis.md
  versioned_docs/version-8.3/reference/announcements.md
  versioned_docs/version-8.3/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-login.md
  versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md
  versioned_docs/version-8.3/self-managed/platform-deployment/manual.md
  versions.json
Labels: kind/cleanup, dx, epic:archive-old-versions

#5597 archive(8.3) removal: logically remove 8.3 docs (reviewable)
  docusaurus.config.js
  src/versions.js
  static/.htaccess
  versions.json
Labels: deploy

#5602 docs: rephrase release note on encrypted communication between Web Modeler components
  docs/reference/announcements-release-notes/860/860-release-notes.md
  versioned_docs/version-8.6/reference/announcements-release-notes/860/860-release-notes.md
  versioned_docs/version-8.7/reference/announcements-release-notes/860/860-release-notes.md
Labels: low prio

#5600 docs: fix a couple preview deploy incorrections
  .github/workflows/preview-env-deploy.yml
Labels: kind/bug, dx

#5479 docs: includeEnabledRecords property documentation
  docs/self-managed/operational-guides/update-guide/870-to-880.md
  docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
  docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
Labels: target:8.8

#5595 CSS for mini-TOC
  src/css/custom.css
Labels: component:docs, deploy, low prio

#5555 docs(assert): add docs for newly implemented asserts
  docs/apis-tools/testing/assertions.md
Labels: target:8.8

#5604 archival: update archival scripts based on de-optimization & only-one-unreleased-version
  hacks/isolateVersion/1-deleteOtherVersions.sh
  hacks/isolateVersion/2-reduceVersionManifest.sh
  hacks/isolateVersion/6-updateCIWorkflows.sh
  hacks/isolateVersion/7-updateDocusaurusConfig.sh
  hacks/isolateVersion/8-configureOptimizeDocs.sh
  hacks/isolateVersion/8-updateCurrentVersion.sh
  hacks/isolateVersion/allSteps.sh
  howtos/versioning.md
Labels: dx

#5605 cleanup: remove optimize instance from howtos, ci checks, etc
  .vale.ini
  hacks/generateOptimizeSidebars.js
  hacks/generateOptimizeSidebars.md
  howtos/configuration.md
  howtos/documentation-guidelines.md
  howtos/markdown-and-mdx-features.md
  howtos/moving-content.md
  howtos/release-procedure.md
  spec/regression/versionMapping.spec.ts
  src/theme/DocItem/Metadata/determineCanonical.js
  src/theme/NavbarItem/index.tsx
  styles/camunda/all/hrefDocsToDocs.yml
  styles/camunda/all/hrefProduction.yml
  styles/camunda/docsInstance/hrefDocsToOptimize.yml
  styles/camunda/optimizeInstance/hrefOptimizeToDocs.yml
  styles/camunda/optimizeInstance/hrefOptimizeToOptimize.yml
Labels: kind/cleanup, dx

#5607 cleanup: remove unnecessary optimize redirects in htaccess
  static/.htaccess
Labels: kind/cleanup, dx

#5584 feat: Add migration guide for decision definition endpoints
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: deploy, low prio

#5610 update gemini connectors link
  docs/components/connectors/out-of-the-box-connectors/google-gemini.md
  versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/google-gemini.md
Labels: kind/bug, component:connectors

#5619 versioning: update scripts and docs
  hacks/cutNewVersions.sh
  howtos/release-procedure.md
Labels: dx

#5574 feat: include guide for using alternative databases with identity
  versioned_docs/version-8.6/self-managed/identity/user-guide/configuration/alternative-db.md
  versioned_sidebars/version-8.6-sidebars.json
Labels: component:identity, component:self-managed, deploy

#5599 docs: add Optimize environment variables to system-config
  docs/self-managed/optimize-deployment/configuration/system-configuration.md
Labels: available & undocumented

#5603 Update versions edit documentation
  docs/components/connectors/img/connector-templates/create-connector-template-3.png
  docs/components/connectors/manage-connector-templates.md
  docs/components/modeler/web-modeler/idp/idp-unstructured-extraction.md
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-actions.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-code-diffing.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-create-process-application-version.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-create-via-icon-highlight.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-restore-complete-highlight.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-restore-highlight.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-view-process-application-version.png
  docs/components/modeler/web-modeler/img/versions/web-modeler-version-visual-diffing.png
  docs/components/modeler/web-modeler/process-application-versioning.md
  docs/components/modeler/web-modeler/versions.md
Labels: component:web-modeler-SaaS, component:web-modeler-sm, deploy, 8.8.0-alpha4

#5615 feat: Migration guide for decision instance endpoints
  docs/apis-tools/migration-manuals/migrate-to-camunda-api.md
Labels: low prio

#5634 chore: update playwright deps to 1.52.0
  package-lock.json
  package.json
Labels: dependencies, dx

#5640 feat: allow for non-self assignment
  docs/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
  versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
Labels: low prio

#5635 chore: bump prettier to 3.5.3
  package-lock.json
  package.json
  src/css/custom.css
Labels: dependencies, dx

#5345 chore: reflected streamlined architecture and naming
  docs/reference/supported-environments.md
Labels: component:self-managed

#5628 chore: clean up 8.7 redirect rules
  static/.htaccess
Labels: dx

#5654 chore: bump mixpanel-browser to 2.64.0
  package-lock.json
  package.json
Labels: dx

#5653 chore: bump form-js to 1.15.1
  package-lock.json
  package.json
Labels: dx, deploy

#5655 chore: bump pushfeedback-react to 0.1.63
  package-lock.json
  package.json
Labels: dependencies, dx

#5660 Remove remaining 8.3 references
  docs/reference/announcements-release-notes/overview.md
  versioned_docs/version-8.3/guides/host-custom-connector.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/deploy.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/aws-marketplace.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/running-custom-connectors.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
  versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
  versioned_docs/version-8.7/reference/announcements-release-notes/overview.md
Labels: kind/bug, component:docs, deploy

#5644 feat: jobError in spring sdk
  docs/apis-tools/spring-zeebe-sdk/configuration.md
Labels: 8.8.0-alpha4

#5661 docs: add guidance for frequent redirect patterns
  howtos/moving-content.md
Labels: dx

#5665 feat(rpa): prominently link to RPA library docs
  sidebars.js
  versioned_sidebars/version-8.7-sidebars.json
Labels: deploy, low prio

#5680 Update Algolia Key
  docusaurus.config.js
Labels: kind/bug, deploy
